// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bid.sql

package sqlcgen

import (
	"context"
	"time"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (auction_id, user_id, amount_in_cents, max_amount_in_cents, idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, auction_id, user_id, amount_in_cents, created_at, updated_at, idempotency_key, max_amount_in_cents
`

type CreateBidParams struct {
	AuctionID        int64
	UserID           int64
	AmountInCents    int64
	MaxAmountInCents *int64
	IdempotencyKey   string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid,
		arg.AuctionID,
		arg.UserID,
		arg.AmountInCents,
		arg.MaxAmountInCents,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.AmountInCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.MaxAmountInCents,
	)
	return i, err
}

const getBidByID = `-- name: GetBidByID :one
SELECT id, auction_id, user_id, amount_in_cents, created_at, updated_at, idempotency_key, max_amount_in_cents FROM bids
WHERE id = $1
`

func (q *Queries) GetBidByID(ctx context.Context, id int64) (Bid, error) {
	row := q.db.QueryRow(ctx, getBidByID, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.AmountInCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.MaxAmountInCents,
	)
	return i, err
}

const listBidsByAuctionID = `-- name: ListBidsByAuctionID :many
SELECT id, auction_id, user_id, amount_in_cents, created_at, updated_at, idempotency_key, max_amount_in_cents FROM bids
WHERE auction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBidsByAuctionID(ctx context.Context, auctionID int64) ([]Bid, error) {
	rows, err := q.db.Query(ctx, listBidsByAuctionID, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.AmountInCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.MaxAmountInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopBidsByAuctionID = `-- name: ListTopBidsByAuctionID :many
SELECT id, auction_id, user_id, amount_in_cents, created_at, updated_at, idempotency_key, max_amount_in_cents FROM bids
WHERE auction_id = $1
ORDER BY amount_in_cents DESC
LIMIT $2
`

type ListTopBidsByAuctionIDParams struct {
	AuctionID int64
	Limit     int32
}

func (q *Queries) ListTopBidsByAuctionID(ctx context.Context, arg ListTopBidsByAuctionIDParams) ([]Bid, error) {
	rows, err := q.db.Query(ctx, listTopBidsByAuctionID, arg.AuctionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.AmountInCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.MaxAmountInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBid = `-- name: UpdateBid :execrows
UPDATE bids
SET updated_at = $1
WHERE id = $2
`

type UpdateBidParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateBid(ctx context.Context, arg UpdateBidParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBid, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
