// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type AuctionState string

const (
	AuctionStateDraft     AuctionState = "draft"
	AuctionStateActive    AuctionState = "active"
	AuctionStateClosed    AuctionState = "closed"
	AuctionStateCancelled AuctionState = "cancelled"
)

func (e *AuctionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionState(s)
	case string:
		*e = AuctionState(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionState: %T", src)
	}
	return nil
}

type NullAuctionState struct {
	AuctionState AuctionState
	Valid        bool // Valid is true if AuctionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionState) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionState), nil
}

type Auction struct {
	ID                      int64
	ListingID               int64
	StartTime               *time.Time
	EndTime                 time.Time
	State                   AuctionState
	HighestBidAmountInCents *int64
	Version                 int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
	TradingMode             string
	StartingPrice           *int64
	PriceStep               *int64
	ReservePrice            *int64
	CurrentPrice            *int64
	WinnerUserID            *int64
	WinningBidID            *int64
	WinningBidAmount        *int64
	AntiSnipeEnabled        bool
	ExtensionWindowSec      int64
	DepositRequired         bool
	DepositAmountInCents    int64
}

type Bid struct {
	ID               int64
	AuctionID        int64
	UserID           int64
	AmountInCents    int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IdempotencyKey   string
	MaxAmountInCents *int64
}

type EventOutbox struct {
	ID            int64
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
	CreatedAt     time.Time
	PublishedAt   *time.Time
}
