// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO event_outbox (event_id, event_type, schema_version, subject, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Subject,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, event_id, event_type, schema_version, subject, payload, occurred_at, created_at, published_at FROM event_outbox
WHERE published_at IS NULL
ORDER BY id ASC
LIMIT $1
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]EventOutbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventOutbox
	for rows.Next() {
		var i EventOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Subject,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :execrows
UPDATE event_outbox
SET published_at = NOW()
WHERE id = $1 AND published_at IS NULL
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
