// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function with given fields: userID, role, email
func (_m *MockTokenService) GenerateAccessToken(userID uint64, role string, email string) (string, time.Time, error) {
	ret := _m.Called(userID, role, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) (string, time.Time, error)); ok {
		return rf(userID, role, email)
	}
	if rf, ok := ret.Get(0).(func(uint64, string, string) string); ok {
		r0 = rf(userID, role, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint64, string, string) time.Time); ok {
		r1 = rf(userID, role, email)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(uint64, string, string) error); ok {
		r2 = rf(userID, role, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uint64
//   - role string
//   - email string
func (_e *MockTokenService_Expecter) GenerateAccessToken(userID interface{}, role interface{}, email interface{}) *MockTokenService_GenerateAccessToken_Call {
	return &MockTokenService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, role, email)}
}

func (_c *MockTokenService_GenerateAccessToken_Call) Run(run func(userID uint64, role string, email string)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) Return(token string, expiresAt time.Time, err error) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(token, expiresAt, err)
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) RunAndReturn(run func(uint64, string, string) (string, time.Time, error)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function with no fields
func (_m *MockTokenService) GenerateRefreshToken() (string, string, time.Time, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 string
	var r2 time.Time
	var r3 error
	if rf, ok := ret.Get(0).(func() (string, string, time.Time, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() time.Time); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(time.Time)
	}

	if rf, ok := ret.Get(3).(func() error); ok {
		r3 = rf()
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTokenService_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenService_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GenerateRefreshToken() *MockTokenService_GenerateRefreshToken_Call {
	return &MockTokenService_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Run(run func()) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Return(raw string, hash string, expiresAt time.Time, err error) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(raw, hash, expiresAt, err)
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) RunAndReturn(run func() (string, string, time.Time, error)) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashRefreshToken provides a mock function with given fields: raw
func (_m *MockTokenService) HashRefreshToken(raw string) string {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for HashRefreshToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(raw)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenService_HashRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashRefreshToken'
type MockTokenService_HashRefreshToken_Call struct {
	*mock.Call
}

// HashRefreshToken is a helper method to define mock.On call
//   - raw string
func (_e *MockTokenService_Expecter) HashRefreshToken(raw interface{}) *MockTokenService_HashRefreshToken_Call {
	return &MockTokenService_HashRefreshToken_Call{Call: _e.mock.On("HashRefreshToken", raw)}
}

func (_c *MockTokenService_HashRefreshToken_Call) Run(run func(raw string)) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_HashRefreshToken_Call) Return(_a0 string) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_HashRefreshToken_Call) RunAndReturn(run func(string) string) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
