// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/listing/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockListingOutboxRepository is an autogenerated mock type for the ListingOutboxRepository type
type MockListingOutboxRepository struct {
	mock.Mock
}

type MockListingOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListingOutboxRepository) EXPECT() *MockListingOutboxRepository_Expecter {
	return &MockListingOutboxRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, event
func (_m *MockListingOutboxRepository) Save(ctx context.Context, event ports.OutboxEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.OutboxEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListingOutboxRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockListingOutboxRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - event ports.OutboxEvent
func (_e *MockListingOutboxRepository_Expecter) Save(ctx interface{}, event interface{}) *MockListingOutboxRepository_Save_Call {
	return &MockListingOutboxRepository_Save_Call{Call: _e.mock.On("Save", ctx, event)}
}

func (_c *MockListingOutboxRepository_Save_Call) Run(run func(ctx context.Context, event ports.OutboxEvent)) *MockListingOutboxRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.OutboxEvent))
	})
	return _c
}

func (_c *MockListingOutboxRepository_Save_Call) Return(_a0 error) *MockListingOutboxRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingOutboxRepository_Save_Call) RunAndReturn(run func(context.Context, ports.OutboxEvent) error) *MockListingOutboxRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListingOutboxRepository creates a new instance of MockListingOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListingOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListingOutboxRepository {
	mock := &MockListingOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
