// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserEmailResolver is an autogenerated mock type for the UserEmailResolver type
type MockUserEmailResolver struct {
	mock.Mock
}

type MockUserEmailResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserEmailResolver) EXPECT() *MockUserEmailResolver_Expecter {
	return &MockUserEmailResolver_Expecter{mock: &_m.Mock}
}

// ResolveEmail provides a mock function with given fields: ctx, userID
func (_m *MockUserEmailResolver) ResolveEmail(ctx context.Context, userID uint64) (string, bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveEmail")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (string, bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) bool); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserEmailResolver_ResolveEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveEmail'
type MockUserEmailResolver_ResolveEmail_Call struct {
	*mock.Call
}

// ResolveEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockUserEmailResolver_Expecter) ResolveEmail(ctx interface{}, userID interface{}) *MockUserEmailResolver_ResolveEmail_Call {
	return &MockUserEmailResolver_ResolveEmail_Call{Call: _e.mock.On("ResolveEmail", ctx, userID)}
}

func (_c *MockUserEmailResolver_ResolveEmail_Call) Run(run func(ctx context.Context, userID uint64)) *MockUserEmailResolver_ResolveEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockUserEmailResolver_ResolveEmail_Call) Return(_a0 string, _a1 bool, _a2 error) *MockUserEmailResolver_ResolveEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserEmailResolver_ResolveEmail_Call) RunAndReturn(run func(context.Context, uint64) (string, bool, error)) *MockUserEmailResolver_ResolveEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserEmailResolver creates a new instance of MockUserEmailResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserEmailResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserEmailResolver {
	mock := &MockUserEmailResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
