// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockListingReadPort is an autogenerated mock type for the ListingReadPort type
type MockListingReadPort struct {
	mock.Mock
}

type MockListingReadPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListingReadPort) EXPECT() *MockListingReadPort_Expecter {
	return &MockListingReadPort_Expecter{mock: &_m.Mock}
}

// FindSpuTitleByID provides a mock function with given fields: ctx, spuID
func (_m *MockListingReadPort) FindSpuTitleByID(ctx context.Context, spuID uint64) (string, bool, error) {
	ret := _m.Called(ctx, spuID)

	if len(ret) == 0 {
		panic("no return value specified for FindSpuTitleByID")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (string, bool, error)); ok {
		return rf(ctx, spuID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = rf(ctx, spuID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) bool); ok {
		r1 = rf(ctx, spuID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, spuID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockListingReadPort_FindSpuTitleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSpuTitleByID'
type MockListingReadPort_FindSpuTitleByID_Call struct {
	*mock.Call
}

// FindSpuTitleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - spuID uint64
func (_e *MockListingReadPort_Expecter) FindSpuTitleByID(ctx interface{}, spuID interface{}) *MockListingReadPort_FindSpuTitleByID_Call {
	return &MockListingReadPort_FindSpuTitleByID_Call{Call: _e.mock.On("FindSpuTitleByID", ctx, spuID)}
}

func (_c *MockListingReadPort_FindSpuTitleByID_Call) Run(run func(ctx context.Context, spuID uint64)) *MockListingReadPort_FindSpuTitleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockListingReadPort_FindSpuTitleByID_Call) Return(_a0 string, _a1 bool, _a2 error) *MockListingReadPort_FindSpuTitleByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockListingReadPort_FindSpuTitleByID_Call) RunAndReturn(run func(context.Context, uint64) (string, bool, error)) *MockListingReadPort_FindSpuTitleByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListingReadPort creates a new instance of MockListingReadPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListingReadPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListingReadPort {
	mock := &MockListingReadPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
