// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/notification/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailPort is an autogenerated mock type for the EmailPort type
type MockEmailPort struct {
	mock.Mock
}

type MockEmailPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailPort) EXPECT() *MockEmailPort_Expecter {
	return &MockEmailPort_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, msg
func (_m *MockEmailPort) Send(ctx context.Context, msg ports.EmailMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.EmailMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailPort_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailPort_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg ports.EmailMessage
func (_e *MockEmailPort_Expecter) Send(ctx interface{}, msg interface{}) *MockEmailPort_Send_Call {
	return &MockEmailPort_Send_Call{Call: _e.mock.On("Send", ctx, msg)}
}

func (_c *MockEmailPort_Send_Call) Run(run func(ctx context.Context, msg ports.EmailMessage)) *MockEmailPort_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.EmailMessage))
	})
	return _c
}

func (_c *MockEmailPort_Send_Call) Return(_a0 error) *MockEmailPort_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailPort_Send_Call) RunAndReturn(run func(context.Context, ports.EmailMessage) error) *MockEmailPort_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailPort creates a new instance of MockEmailPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailPort {
	mock := &MockEmailPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
