// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/ledger/domain/model"
	ports "auction/internal/modules/ledger/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLedgerAccountService is an autogenerated mock type for the LedgerAccountService type
type MockLedgerAccountService struct {
	mock.Mock
}

type MockLedgerAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerAccountService) EXPECT() *MockLedgerAccountService_Expecter {
	return &MockLedgerAccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, owner, currency
func (_m *MockLedgerAccountService) CreateAccount(ctx context.Context, owner string, currency string) (model.AccountModel, error) {
	ret := _m.Called(ctx, owner, currency)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 model.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.AccountModel, error)); ok {
		return rf(ctx, owner, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.AccountModel); ok {
		r0 = rf(ctx, owner, currency)
	} else {
		r0 = ret.Get(0).(model.AccountModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, owner, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockLedgerAccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - currency string
func (_e *MockLedgerAccountService_Expecter) CreateAccount(ctx interface{}, owner interface{}, currency interface{}) *MockLedgerAccountService_CreateAccount_Call {
	return &MockLedgerAccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, owner, currency)}
}

func (_c *MockLedgerAccountService_CreateAccount_Call) Run(run func(ctx context.Context, owner string, currency string)) *MockLedgerAccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLedgerAccountService_CreateAccount_Call) Return(_a0 model.AccountModel, _a1 error) *MockLedgerAccountService_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_CreateAccount_Call) RunAndReturn(run func(context.Context, string, string) (model.AccountModel, error)) *MockLedgerAccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Freeze provides a mock function with given fields: ctx, input
func (_m *MockLedgerAccountService) Freeze(ctx context.Context, input ports.FreezeInput) (model.OperationModel, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Freeze")
	}

	var r0 model.OperationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.FreezeInput) (model.OperationModel, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.FreezeInput) model.OperationModel); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.OperationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.FreezeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_Freeze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Freeze'
type MockLedgerAccountService_Freeze_Call struct {
	*mock.Call
}

// Freeze is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.FreezeInput
func (_e *MockLedgerAccountService_Expecter) Freeze(ctx interface{}, input interface{}) *MockLedgerAccountService_Freeze_Call {
	return &MockLedgerAccountService_Freeze_Call{Call: _e.mock.On("Freeze", ctx, input)}
}

func (_c *MockLedgerAccountService_Freeze_Call) Run(run func(ctx context.Context, input ports.FreezeInput)) *MockLedgerAccountService_Freeze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.FreezeInput))
	})
	return _c
}

func (_c *MockLedgerAccountService_Freeze_Call) Return(_a0 model.OperationModel, _a1 error) *MockLedgerAccountService_Freeze_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_Freeze_Call) RunAndReturn(run func(context.Context, ports.FreezeInput) (model.OperationModel, error)) *MockLedgerAccountService_Freeze_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function with given fields: ctx, id
func (_m *MockLedgerAccountService) GetAccountByID(ctx context.Context, id uint64) (model.AccountModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 model.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.AccountModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.AccountModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AccountModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type MockLedgerAccountService_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockLedgerAccountService_Expecter) GetAccountByID(ctx interface{}, id interface{}) *MockLedgerAccountService_GetAccountByID_Call {
	return &MockLedgerAccountService_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, id)}
}

func (_c *MockLedgerAccountService_GetAccountByID_Call) Run(run func(ctx context.Context, id uint64)) *MockLedgerAccountService_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockLedgerAccountService_GetAccountByID_Call) Return(_a0 model.AccountModel, _a1 error) *MockLedgerAccountService_GetAccountByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_GetAccountByID_Call) RunAndReturn(run func(context.Context, uint64) (model.AccountModel, error)) *MockLedgerAccountService_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByOwner provides a mock function with given fields: ctx, owner, currency
func (_m *MockLedgerAccountService) GetAccountByOwner(ctx context.Context, owner string, currency string) (model.AccountModel, error) {
	ret := _m.Called(ctx, owner, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByOwner")
	}

	var r0 model.AccountModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.AccountModel, error)); ok {
		return rf(ctx, owner, currency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.AccountModel); ok {
		r0 = rf(ctx, owner, currency)
	} else {
		r0 = ret.Get(0).(model.AccountModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, owner, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_GetAccountByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByOwner'
type MockLedgerAccountService_GetAccountByOwner_Call struct {
	*mock.Call
}

// GetAccountByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - currency string
func (_e *MockLedgerAccountService_Expecter) GetAccountByOwner(ctx interface{}, owner interface{}, currency interface{}) *MockLedgerAccountService_GetAccountByOwner_Call {
	return &MockLedgerAccountService_GetAccountByOwner_Call{Call: _e.mock.On("GetAccountByOwner", ctx, owner, currency)}
}

func (_c *MockLedgerAccountService_GetAccountByOwner_Call) Run(run func(ctx context.Context, owner string, currency string)) *MockLedgerAccountService_GetAccountByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLedgerAccountService_GetAccountByOwner_Call) Return(_a0 model.AccountModel, _a1 error) *MockLedgerAccountService_GetAccountByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_GetAccountByOwner_Call) RunAndReturn(run func(context.Context, string, string) (model.AccountModel, error)) *MockLedgerAccountService_GetAccountByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function with given fields: ctx, input
func (_m *MockLedgerAccountService) Transfer(ctx context.Context, input ports.TransferInput) (model.TransferModel, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 model.TransferModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.TransferInput) (model.TransferModel, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.TransferInput) model.TransferModel); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.TransferModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.TransferInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type MockLedgerAccountService_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.TransferInput
func (_e *MockLedgerAccountService_Expecter) Transfer(ctx interface{}, input interface{}) *MockLedgerAccountService_Transfer_Call {
	return &MockLedgerAccountService_Transfer_Call{Call: _e.mock.On("Transfer", ctx, input)}
}

func (_c *MockLedgerAccountService_Transfer_Call) Run(run func(ctx context.Context, input ports.TransferInput)) *MockLedgerAccountService_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.TransferInput))
	})
	return _c
}

func (_c *MockLedgerAccountService_Transfer_Call) Return(_a0 model.TransferModel, _a1 error) *MockLedgerAccountService_Transfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_Transfer_Call) RunAndReturn(run func(context.Context, ports.TransferInput) (model.TransferModel, error)) *MockLedgerAccountService_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Unfreeze provides a mock function with given fields: ctx, input
func (_m *MockLedgerAccountService) Unfreeze(ctx context.Context, input ports.UnfreezeInput) (model.OperationModel, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Unfreeze")
	}

	var r0 model.OperationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.UnfreezeInput) (model.OperationModel, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.UnfreezeInput) model.OperationModel); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.OperationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.UnfreezeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_Unfreeze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfreeze'
type MockLedgerAccountService_Unfreeze_Call struct {
	*mock.Call
}

// Unfreeze is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.UnfreezeInput
func (_e *MockLedgerAccountService_Expecter) Unfreeze(ctx interface{}, input interface{}) *MockLedgerAccountService_Unfreeze_Call {
	return &MockLedgerAccountService_Unfreeze_Call{Call: _e.mock.On("Unfreeze", ctx, input)}
}

func (_c *MockLedgerAccountService_Unfreeze_Call) Run(run func(ctx context.Context, input ports.UnfreezeInput)) *MockLedgerAccountService_Unfreeze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.UnfreezeInput))
	})
	return _c
}

func (_c *MockLedgerAccountService_Unfreeze_Call) Return(_a0 model.OperationModel, _a1 error) *MockLedgerAccountService_Unfreeze_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_Unfreeze_Call) RunAndReturn(run func(context.Context, ports.UnfreezeInput) (model.OperationModel, error)) *MockLedgerAccountService_Unfreeze_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawFromFrozen provides a mock function with given fields: ctx, input
func (_m *MockLedgerAccountService) WithdrawFromFrozen(ctx context.Context, input ports.WithdrawFromFrozenInput) (model.OperationModel, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawFromFrozen")
	}

	var r0 model.OperationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.WithdrawFromFrozenInput) (model.OperationModel, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.WithdrawFromFrozenInput) model.OperationModel); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.OperationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.WithdrawFromFrozenInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerAccountService_WithdrawFromFrozen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawFromFrozen'
type MockLedgerAccountService_WithdrawFromFrozen_Call struct {
	*mock.Call
}

// WithdrawFromFrozen is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.WithdrawFromFrozenInput
func (_e *MockLedgerAccountService_Expecter) WithdrawFromFrozen(ctx interface{}, input interface{}) *MockLedgerAccountService_WithdrawFromFrozen_Call {
	return &MockLedgerAccountService_WithdrawFromFrozen_Call{Call: _e.mock.On("WithdrawFromFrozen", ctx, input)}
}

func (_c *MockLedgerAccountService_WithdrawFromFrozen_Call) Run(run func(ctx context.Context, input ports.WithdrawFromFrozenInput)) *MockLedgerAccountService_WithdrawFromFrozen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.WithdrawFromFrozenInput))
	})
	return _c
}

func (_c *MockLedgerAccountService_WithdrawFromFrozen_Call) Return(_a0 model.OperationModel, _a1 error) *MockLedgerAccountService_WithdrawFromFrozen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerAccountService_WithdrawFromFrozen_Call) RunAndReturn(run func(context.Context, ports.WithdrawFromFrozenInput) (model.OperationModel, error)) *MockLedgerAccountService_WithdrawFromFrozen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerAccountService creates a new instance of MockLedgerAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerAccountService {
	mock := &MockLedgerAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
