// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/listing/domain/model"
	ports "auction/internal/modules/listing/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSpuRepository is an autogenerated mock type for the SpuRepository type
type MockSpuRepository struct {
	mock.Mock
}

type MockSpuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpuRepository) EXPECT() *MockSpuRepository_Expecter {
	return &MockSpuRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, filter
func (_m *MockSpuRepository) Count(ctx context.Context, filter ports.ListSpusFilter) (uint64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListSpusFilter) (uint64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListSpusFilter) uint64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.ListSpusFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpuRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSpuRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.ListSpusFilter
func (_e *MockSpuRepository_Expecter) Count(ctx interface{}, filter interface{}) *MockSpuRepository_Count_Call {
	return &MockSpuRepository_Count_Call{Call: _e.mock.On("Count", ctx, filter)}
}

func (_c *MockSpuRepository_Count_Call) Run(run func(ctx context.Context, filter ports.ListSpusFilter)) *MockSpuRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.ListSpusFilter))
	})
	return _c
}

func (_c *MockSpuRepository_Count_Call) Return(_a0 uint64, _a1 error) *MockSpuRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpuRepository_Count_Call) RunAndReturn(run func(context.Context, ports.ListSpusFilter) (uint64, error)) *MockSpuRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, spu
func (_m *MockSpuRepository) Create(ctx context.Context, spu model.SpuModel) (model.SpuModel, error) {
	ret := _m.Called(ctx, spu)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.SpuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SpuModel) (model.SpuModel, error)); ok {
		return rf(ctx, spu)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SpuModel) model.SpuModel); ok {
		r0 = rf(ctx, spu)
	} else {
		r0 = ret.Get(0).(model.SpuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SpuModel) error); ok {
		r1 = rf(ctx, spu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpuRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSpuRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spu model.SpuModel
func (_e *MockSpuRepository_Expecter) Create(ctx interface{}, spu interface{}) *MockSpuRepository_Create_Call {
	return &MockSpuRepository_Create_Call{Call: _e.mock.On("Create", ctx, spu)}
}

func (_c *MockSpuRepository_Create_Call) Run(run func(ctx context.Context, spu model.SpuModel)) *MockSpuRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SpuModel))
	})
	return _c
}

func (_c *MockSpuRepository_Create_Call) Return(_a0 model.SpuModel, _a1 error) *MockSpuRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpuRepository_Create_Call) RunAndReturn(run func(context.Context, model.SpuModel) (model.SpuModel, error)) *MockSpuRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSpuRepository) FindByID(ctx context.Context, id uint64) (model.SpuModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.SpuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.SpuModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.SpuModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.SpuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpuRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSpuRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockSpuRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSpuRepository_FindByID_Call {
	return &MockSpuRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSpuRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockSpuRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSpuRepository_FindByID_Call) Return(_a0 model.SpuModel, _a1 error) *MockSpuRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpuRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.SpuModel, error)) *MockSpuRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *MockSpuRepository) FindByIDForUpdate(ctx context.Context, id uint64) (model.SpuModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 model.SpuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.SpuModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.SpuModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.SpuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpuRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockSpuRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockSpuRepository_Expecter) FindByIDForUpdate(ctx interface{}, id interface{}) *MockSpuRepository_FindByIDForUpdate_Call {
	return &MockSpuRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, id)}
}

func (_c *MockSpuRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, id uint64)) *MockSpuRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSpuRepository_FindByIDForUpdate_Call) Return(_a0 model.SpuModel, _a1 error) *MockSpuRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpuRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, uint64) (model.SpuModel, error)) *MockSpuRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockSpuRepository) List(ctx context.Context, filter ports.ListSpusFilter) ([]model.SpuModel, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.SpuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListSpusFilter) ([]model.SpuModel, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListSpusFilter) []model.SpuModel); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SpuModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.ListSpusFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpuRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSpuRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.ListSpusFilter
func (_e *MockSpuRepository_Expecter) List(ctx interface{}, filter interface{}) *MockSpuRepository_List_Call {
	return &MockSpuRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockSpuRepository_List_Call) Run(run func(ctx context.Context, filter ports.ListSpusFilter)) *MockSpuRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.ListSpusFilter))
	})
	return _c
}

func (_c *MockSpuRepository_List_Call) Return(_a0 []model.SpuModel, _a1 error) *MockSpuRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpuRepository_List_Call) RunAndReturn(run func(context.Context, ports.ListSpusFilter) ([]model.SpuModel, error)) *MockSpuRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, spu
func (_m *MockSpuRepository) Update(ctx context.Context, spu model.SpuModel) error {
	ret := _m.Called(ctx, spu)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SpuModel) error); ok {
		r0 = rf(ctx, spu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSpuRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSpuRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - spu model.SpuModel
func (_e *MockSpuRepository_Expecter) Update(ctx interface{}, spu interface{}) *MockSpuRepository_Update_Call {
	return &MockSpuRepository_Update_Call{Call: _e.mock.On("Update", ctx, spu)}
}

func (_c *MockSpuRepository_Update_Call) Run(run func(ctx context.Context, spu model.SpuModel)) *MockSpuRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SpuModel))
	})
	return _c
}

func (_c *MockSpuRepository_Update_Call) Return(_a0 error) *MockSpuRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSpuRepository_Update_Call) RunAndReturn(run func(context.Context, model.SpuModel) error) *MockSpuRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpuRepository creates a new instance of MockSpuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpuRepository {
	mock := &MockSpuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
