// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ledgerports "auction/internal/modules/ledger/ports"
	ports "auction/internal/modules/payment/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentUnitOfWork is an autogenerated mock type for the PaymentUnitOfWork type
type MockPaymentUnitOfWork struct {
	mock.Mock
}

type MockPaymentUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentUnitOfWork) EXPECT() *MockPaymentUnitOfWork_Expecter {
	return &MockPaymentUnitOfWork_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx
func (_m *MockPaymentUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockPaymentUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentUnitOfWork_Expecter) Complete(ctx interface{}) *MockPaymentUnitOfWork_Complete_Call {
	return &MockPaymentUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockPaymentUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockPaymentUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_Complete_Call) Return(_a0 error) *MockPaymentUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockPaymentUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// LedgerRepository provides a mock function with no fields
func (_m *MockPaymentUnitOfWork) LedgerRepository() ledgerports.LedgerRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LedgerRepository")
	}

	var r0 ledgerports.LedgerRepository
	if rf, ok := ret.Get(0).(func() ledgerports.LedgerRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ledgerports.LedgerRepository)
		}
	}

	return r0
}

// MockPaymentUnitOfWork_LedgerRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LedgerRepository'
type MockPaymentUnitOfWork_LedgerRepository_Call struct {
	*mock.Call
}

// LedgerRepository is a helper method to define mock.On call
func (_e *MockPaymentUnitOfWork_Expecter) LedgerRepository() *MockPaymentUnitOfWork_LedgerRepository_Call {
	return &MockPaymentUnitOfWork_LedgerRepository_Call{Call: _e.mock.On("LedgerRepository")}
}

func (_c *MockPaymentUnitOfWork_LedgerRepository_Call) Run(run func()) *MockPaymentUnitOfWork_LedgerRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_LedgerRepository_Call) Return(_a0 ledgerports.LedgerRepository) *MockPaymentUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_LedgerRepository_Call) RunAndReturn(run func() ledgerports.LedgerRepository) *MockPaymentUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(run)
	return _c
}

// OutboxRepository provides a mock function with no fields
func (_m *MockPaymentUnitOfWork) OutboxRepository() ports.PaymentOutboxRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutboxRepository")
	}

	var r0 ports.PaymentOutboxRepository
	if rf, ok := ret.Get(0).(func() ports.PaymentOutboxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.PaymentOutboxRepository)
		}
	}

	return r0
}

// MockPaymentUnitOfWork_OutboxRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutboxRepository'
type MockPaymentUnitOfWork_OutboxRepository_Call struct {
	*mock.Call
}

// OutboxRepository is a helper method to define mock.On call
func (_e *MockPaymentUnitOfWork_Expecter) OutboxRepository() *MockPaymentUnitOfWork_OutboxRepository_Call {
	return &MockPaymentUnitOfWork_OutboxRepository_Call{Call: _e.mock.On("OutboxRepository")}
}

func (_c *MockPaymentUnitOfWork_OutboxRepository_Call) Run(run func()) *MockPaymentUnitOfWork_OutboxRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_OutboxRepository_Call) Return(_a0 ports.PaymentOutboxRepository) *MockPaymentUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_OutboxRepository_Call) RunAndReturn(run func() ports.PaymentOutboxRepository) *MockPaymentUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentRepository provides a mock function with no fields
func (_m *MockPaymentUnitOfWork) PaymentRepository() ports.PaymentRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PaymentRepository")
	}

	var r0 ports.PaymentRepository
	if rf, ok := ret.Get(0).(func() ports.PaymentRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.PaymentRepository)
		}
	}

	return r0
}

// MockPaymentUnitOfWork_PaymentRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentRepository'
type MockPaymentUnitOfWork_PaymentRepository_Call struct {
	*mock.Call
}

// PaymentRepository is a helper method to define mock.On call
func (_e *MockPaymentUnitOfWork_Expecter) PaymentRepository() *MockPaymentUnitOfWork_PaymentRepository_Call {
	return &MockPaymentUnitOfWork_PaymentRepository_Call{Call: _e.mock.On("PaymentRepository")}
}

func (_c *MockPaymentUnitOfWork_PaymentRepository_Call) Run(run func()) *MockPaymentUnitOfWork_PaymentRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_PaymentRepository_Call) Return(_a0 ports.PaymentRepository) *MockPaymentUnitOfWork_PaymentRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_PaymentRepository_Call) RunAndReturn(run func() ports.PaymentRepository) *MockPaymentUnitOfWork_PaymentRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockPaymentUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockPaymentUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentUnitOfWork_Expecter) Rollback(ctx interface{}) *MockPaymentUnitOfWork_Rollback_Call {
	return &MockPaymentUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockPaymentUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockPaymentUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_Rollback_Call) Return(_a0 error) *MockPaymentUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockPaymentUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawalRepository provides a mock function with no fields
func (_m *MockPaymentUnitOfWork) WithdrawalRepository() ports.WithdrawalRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithdrawalRepository")
	}

	var r0 ports.WithdrawalRepository
	if rf, ok := ret.Get(0).(func() ports.WithdrawalRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.WithdrawalRepository)
		}
	}

	return r0
}

// MockPaymentUnitOfWork_WithdrawalRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawalRepository'
type MockPaymentUnitOfWork_WithdrawalRepository_Call struct {
	*mock.Call
}

// WithdrawalRepository is a helper method to define mock.On call
func (_e *MockPaymentUnitOfWork_Expecter) WithdrawalRepository() *MockPaymentUnitOfWork_WithdrawalRepository_Call {
	return &MockPaymentUnitOfWork_WithdrawalRepository_Call{Call: _e.mock.On("WithdrawalRepository")}
}

func (_c *MockPaymentUnitOfWork_WithdrawalRepository_Call) Run(run func()) *MockPaymentUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentUnitOfWork_WithdrawalRepository_Call) Return(_a0 ports.WithdrawalRepository) *MockPaymentUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentUnitOfWork_WithdrawalRepository_Call) RunAndReturn(run func() ports.WithdrawalRepository) *MockPaymentUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentUnitOfWork creates a new instance of MockPaymentUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentUnitOfWork {
	mock := &MockPaymentUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
