// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/notification/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationUnitOfWork is an autogenerated mock type for the NotificationUnitOfWork type
type MockNotificationUnitOfWork struct {
	mock.Mock
}

type MockNotificationUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationUnitOfWork) EXPECT() *MockNotificationUnitOfWork_Expecter {
	return &MockNotificationUnitOfWork_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx
func (_m *MockNotificationUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockNotificationUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotificationUnitOfWork_Expecter) Complete(ctx interface{}) *MockNotificationUnitOfWork_Complete_Call {
	return &MockNotificationUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockNotificationUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockNotificationUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNotificationUnitOfWork_Complete_Call) Return(_a0 error) *MockNotificationUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockNotificationUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// NotificationRepository provides a mock function with no fields
func (_m *MockNotificationUnitOfWork) NotificationRepository() ports.NotificationRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotificationRepository")
	}

	var r0 ports.NotificationRepository
	if rf, ok := ret.Get(0).(func() ports.NotificationRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.NotificationRepository)
		}
	}

	return r0
}

// MockNotificationUnitOfWork_NotificationRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotificationRepository'
type MockNotificationUnitOfWork_NotificationRepository_Call struct {
	*mock.Call
}

// NotificationRepository is a helper method to define mock.On call
func (_e *MockNotificationUnitOfWork_Expecter) NotificationRepository() *MockNotificationUnitOfWork_NotificationRepository_Call {
	return &MockNotificationUnitOfWork_NotificationRepository_Call{Call: _e.mock.On("NotificationRepository")}
}

func (_c *MockNotificationUnitOfWork_NotificationRepository_Call) Run(run func()) *MockNotificationUnitOfWork_NotificationRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationUnitOfWork_NotificationRepository_Call) Return(_a0 ports.NotificationRepository) *MockNotificationUnitOfWork_NotificationRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUnitOfWork_NotificationRepository_Call) RunAndReturn(run func() ports.NotificationRepository) *MockNotificationUnitOfWork_NotificationRepository_Call {
	_c.Call.Return(run)
	return _c
}

// OutboxRepository provides a mock function with no fields
func (_m *MockNotificationUnitOfWork) OutboxRepository() ports.NotificationOutboxRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutboxRepository")
	}

	var r0 ports.NotificationOutboxRepository
	if rf, ok := ret.Get(0).(func() ports.NotificationOutboxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.NotificationOutboxRepository)
		}
	}

	return r0
}

// MockNotificationUnitOfWork_OutboxRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutboxRepository'
type MockNotificationUnitOfWork_OutboxRepository_Call struct {
	*mock.Call
}

// OutboxRepository is a helper method to define mock.On call
func (_e *MockNotificationUnitOfWork_Expecter) OutboxRepository() *MockNotificationUnitOfWork_OutboxRepository_Call {
	return &MockNotificationUnitOfWork_OutboxRepository_Call{Call: _e.mock.On("OutboxRepository")}
}

func (_c *MockNotificationUnitOfWork_OutboxRepository_Call) Run(run func()) *MockNotificationUnitOfWork_OutboxRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationUnitOfWork_OutboxRepository_Call) Return(_a0 ports.NotificationOutboxRepository) *MockNotificationUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUnitOfWork_OutboxRepository_Call) RunAndReturn(run func() ports.NotificationOutboxRepository) *MockNotificationUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PreferenceRepository provides a mock function with no fields
func (_m *MockNotificationUnitOfWork) PreferenceRepository() ports.PreferenceRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreferenceRepository")
	}

	var r0 ports.PreferenceRepository
	if rf, ok := ret.Get(0).(func() ports.PreferenceRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.PreferenceRepository)
		}
	}

	return r0
}

// MockNotificationUnitOfWork_PreferenceRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreferenceRepository'
type MockNotificationUnitOfWork_PreferenceRepository_Call struct {
	*mock.Call
}

// PreferenceRepository is a helper method to define mock.On call
func (_e *MockNotificationUnitOfWork_Expecter) PreferenceRepository() *MockNotificationUnitOfWork_PreferenceRepository_Call {
	return &MockNotificationUnitOfWork_PreferenceRepository_Call{Call: _e.mock.On("PreferenceRepository")}
}

func (_c *MockNotificationUnitOfWork_PreferenceRepository_Call) Run(run func()) *MockNotificationUnitOfWork_PreferenceRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationUnitOfWork_PreferenceRepository_Call) Return(_a0 ports.PreferenceRepository) *MockNotificationUnitOfWork_PreferenceRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUnitOfWork_PreferenceRepository_Call) RunAndReturn(run func() ports.PreferenceRepository) *MockNotificationUnitOfWork_PreferenceRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockNotificationUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockNotificationUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotificationUnitOfWork_Expecter) Rollback(ctx interface{}) *MockNotificationUnitOfWork_Rollback_Call {
	return &MockNotificationUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockNotificationUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockNotificationUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNotificationUnitOfWork_Rollback_Call) Return(_a0 error) *MockNotificationUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockNotificationUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationUnitOfWork creates a new instance of MockNotificationUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationUnitOfWork {
	mock := &MockNotificationUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
