// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	strategy "auction/internal/modules/auction/domain/strategy"

	mock "github.com/stretchr/testify/mock"
)

// MockProxyResolvable is an autogenerated mock type for the ProxyResolvable type
type MockProxyResolvable struct {
	mock.Mock
}

type MockProxyResolvable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProxyResolvable) EXPECT() *MockProxyResolvable_Expecter {
	return &MockProxyResolvable_Expecter{mock: &_m.Mock}
}

// ResolveProxyBids provides a mock function with given fields: auction, existing, newBidder, newMax
func (_m *MockProxyResolvable) ResolveProxyBids(auction strategy.AuctionView, existing []strategy.BidView, newBidder uint64, newMax strategy.MoneyView) ([]strategy.ProxyAction, error) {
	ret := _m.Called(auction, existing, newBidder, newMax)

	if len(ret) == 0 {
		panic("no return value specified for ResolveProxyBids")
	}

	var r0 []strategy.ProxyAction
	var r1 error
	if rf, ok := ret.Get(0).(func(strategy.AuctionView, []strategy.BidView, uint64, strategy.MoneyView) ([]strategy.ProxyAction, error)); ok {
		return rf(auction, existing, newBidder, newMax)
	}
	if rf, ok := ret.Get(0).(func(strategy.AuctionView, []strategy.BidView, uint64, strategy.MoneyView) []strategy.ProxyAction); ok {
		r0 = rf(auction, existing, newBidder, newMax)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]strategy.ProxyAction)
		}
	}

	if rf, ok := ret.Get(1).(func(strategy.AuctionView, []strategy.BidView, uint64, strategy.MoneyView) error); ok {
		r1 = rf(auction, existing, newBidder, newMax)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProxyResolvable_ResolveProxyBids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveProxyBids'
type MockProxyResolvable_ResolveProxyBids_Call struct {
	*mock.Call
}

// ResolveProxyBids is a helper method to define mock.On call
//   - auction strategy.AuctionView
//   - existing []strategy.BidView
//   - newBidder uint64
//   - newMax strategy.MoneyView
func (_e *MockProxyResolvable_Expecter) ResolveProxyBids(auction interface{}, existing interface{}, newBidder interface{}, newMax interface{}) *MockProxyResolvable_ResolveProxyBids_Call {
	return &MockProxyResolvable_ResolveProxyBids_Call{Call: _e.mock.On("ResolveProxyBids", auction, existing, newBidder, newMax)}
}

func (_c *MockProxyResolvable_ResolveProxyBids_Call) Run(run func(auction strategy.AuctionView, existing []strategy.BidView, newBidder uint64, newMax strategy.MoneyView)) *MockProxyResolvable_ResolveProxyBids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(strategy.AuctionView), args[1].([]strategy.BidView), args[2].(uint64), args[3].(strategy.MoneyView))
	})
	return _c
}

func (_c *MockProxyResolvable_ResolveProxyBids_Call) Return(_a0 []strategy.ProxyAction, _a1 error) *MockProxyResolvable_ResolveProxyBids_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProxyResolvable_ResolveProxyBids_Call) RunAndReturn(run func(strategy.AuctionView, []strategy.BidView, uint64, strategy.MoneyView) ([]strategy.ProxyAction, error)) *MockProxyResolvable_ResolveProxyBids_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProxyResolvable creates a new instance of MockProxyResolvable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProxyResolvable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProxyResolvable {
	mock := &MockProxyResolvable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
