// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/auction/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBidRepository is an autogenerated mock type for the BidRepository type
type MockBidRepository struct {
	mock.Mock
}

type MockBidRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBidRepository) EXPECT() *MockBidRepository_Expecter {
	return &MockBidRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, bid, idempotencyKey
func (_m *MockBidRepository) Create(ctx context.Context, bid model.BidModel, idempotencyKey string) (model.BidModel, error) {
	ret := _m.Called(ctx, bid, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.BidModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BidModel, string) (model.BidModel, error)); ok {
		return rf(ctx, bid, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BidModel, string) model.BidModel); ok {
		r0 = rf(ctx, bid, idempotencyKey)
	} else {
		r0 = ret.Get(0).(model.BidModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BidModel, string) error); ok {
		r1 = rf(ctx, bid, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBidRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - bid model.BidModel
//   - idempotencyKey string
func (_e *MockBidRepository_Expecter) Create(ctx interface{}, bid interface{}, idempotencyKey interface{}) *MockBidRepository_Create_Call {
	return &MockBidRepository_Create_Call{Call: _e.mock.On("Create", ctx, bid, idempotencyKey)}
}

func (_c *MockBidRepository_Create_Call) Run(run func(ctx context.Context, bid model.BidModel, idempotencyKey string)) *MockBidRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BidModel), args[2].(string))
	})
	return _c
}

func (_c *MockBidRepository_Create_Call) Return(_a0 model.BidModel, _a1 error) *MockBidRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidRepository_Create_Call) RunAndReturn(run func(context.Context, model.BidModel, string) (model.BidModel, error)) *MockBidRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAuctionID provides a mock function with given fields: ctx, auctionID
func (_m *MockBidRepository) FindByAuctionID(ctx context.Context, auctionID uint64) ([]model.BidModel, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAuctionID")
	}

	var r0 []model.BidModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.BidModel, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.BidModel); ok {
		r0 = rf(ctx, auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BidModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidRepository_FindByAuctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAuctionID'
type MockBidRepository_FindByAuctionID_Call struct {
	*mock.Call
}

// FindByAuctionID is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
func (_e *MockBidRepository_Expecter) FindByAuctionID(ctx interface{}, auctionID interface{}) *MockBidRepository_FindByAuctionID_Call {
	return &MockBidRepository_FindByAuctionID_Call{Call: _e.mock.On("FindByAuctionID", ctx, auctionID)}
}

func (_c *MockBidRepository_FindByAuctionID_Call) Run(run func(ctx context.Context, auctionID uint64)) *MockBidRepository_FindByAuctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockBidRepository_FindByAuctionID_Call) Return(_a0 []model.BidModel, _a1 error) *MockBidRepository_FindByAuctionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidRepository_FindByAuctionID_Call) RunAndReturn(run func(context.Context, uint64) ([]model.BidModel, error)) *MockBidRepository_FindByAuctionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBidRepository) FindByID(ctx context.Context, id uint64) (model.BidModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.BidModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.BidModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.BidModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.BidModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBidRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockBidRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBidRepository_FindByID_Call {
	return &MockBidRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBidRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockBidRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockBidRepository_FindByID_Call) Return(_a0 model.BidModel, _a1 error) *MockBidRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.BidModel, error)) *MockBidRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindTopBidsByAuctionID provides a mock function with given fields: ctx, auctionID, limit
func (_m *MockBidRepository) FindTopBidsByAuctionID(ctx context.Context, auctionID uint64, limit int) ([]model.BidModel, error) {
	ret := _m.Called(ctx, auctionID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindTopBidsByAuctionID")
	}

	var r0 []model.BidModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int) ([]model.BidModel, error)); ok {
		return rf(ctx, auctionID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int) []model.BidModel); ok {
		r0 = rf(ctx, auctionID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BidModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int) error); ok {
		r1 = rf(ctx, auctionID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidRepository_FindTopBidsByAuctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTopBidsByAuctionID'
type MockBidRepository_FindTopBidsByAuctionID_Call struct {
	*mock.Call
}

// FindTopBidsByAuctionID is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
//   - limit int
func (_e *MockBidRepository_Expecter) FindTopBidsByAuctionID(ctx interface{}, auctionID interface{}, limit interface{}) *MockBidRepository_FindTopBidsByAuctionID_Call {
	return &MockBidRepository_FindTopBidsByAuctionID_Call{Call: _e.mock.On("FindTopBidsByAuctionID", ctx, auctionID, limit)}
}

func (_c *MockBidRepository_FindTopBidsByAuctionID_Call) Run(run func(ctx context.Context, auctionID uint64, limit int)) *MockBidRepository_FindTopBidsByAuctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int))
	})
	return _c
}

func (_c *MockBidRepository_FindTopBidsByAuctionID_Call) Return(_a0 []model.BidModel, _a1 error) *MockBidRepository_FindTopBidsByAuctionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidRepository_FindTopBidsByAuctionID_Call) RunAndReturn(run func(context.Context, uint64, int) ([]model.BidModel, error)) *MockBidRepository_FindTopBidsByAuctionID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, bid
func (_m *MockBidRepository) Update(ctx context.Context, bid model.BidModel) error {
	ret := _m.Called(ctx, bid)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BidModel) error); ok {
		r0 = rf(ctx, bid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBidRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - bid model.BidModel
func (_e *MockBidRepository_Expecter) Update(ctx interface{}, bid interface{}) *MockBidRepository_Update_Call {
	return &MockBidRepository_Update_Call{Call: _e.mock.On("Update", ctx, bid)}
}

func (_c *MockBidRepository_Update_Call) Run(run func(ctx context.Context, bid model.BidModel)) *MockBidRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BidModel))
	})
	return _c
}

func (_c *MockBidRepository_Update_Call) Return(_a0 error) *MockBidRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidRepository_Update_Call) RunAndReturn(run func(context.Context, model.BidModel) error) *MockBidRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBidRepository creates a new instance of MockBidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBidRepository {
	mock := &MockBidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
