// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/payment/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type MockWithdrawalRepository struct {
	mock.Mock
}

type MockWithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdrawalRepository) EXPECT() *MockWithdrawalRepository_Expecter {
	return &MockWithdrawalRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockWithdrawalRepository) FindByID(ctx context.Context, id uint64) (model.WithdrawalModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.WithdrawalModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.WithdrawalModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.WithdrawalModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.WithdrawalModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawalRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWithdrawalRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockWithdrawalRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockWithdrawalRepository_FindByID_Call {
	return &MockWithdrawalRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockWithdrawalRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockWithdrawalRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockWithdrawalRepository_FindByID_Call) Return(_a0 model.WithdrawalModel, _a1 error) *MockWithdrawalRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawalRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.WithdrawalModel, error)) *MockWithdrawalRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOutBizNo provides a mock function with given fields: ctx, outBizNo
func (_m *MockWithdrawalRepository) FindByOutBizNo(ctx context.Context, outBizNo string) (model.WithdrawalModel, error) {
	ret := _m.Called(ctx, outBizNo)

	if len(ret) == 0 {
		panic("no return value specified for FindByOutBizNo")
	}

	var r0 model.WithdrawalModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.WithdrawalModel, error)); ok {
		return rf(ctx, outBizNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.WithdrawalModel); ok {
		r0 = rf(ctx, outBizNo)
	} else {
		r0 = ret.Get(0).(model.WithdrawalModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, outBizNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawalRepository_FindByOutBizNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOutBizNo'
type MockWithdrawalRepository_FindByOutBizNo_Call struct {
	*mock.Call
}

// FindByOutBizNo is a helper method to define mock.On call
//   - ctx context.Context
//   - outBizNo string
func (_e *MockWithdrawalRepository_Expecter) FindByOutBizNo(ctx interface{}, outBizNo interface{}) *MockWithdrawalRepository_FindByOutBizNo_Call {
	return &MockWithdrawalRepository_FindByOutBizNo_Call{Call: _e.mock.On("FindByOutBizNo", ctx, outBizNo)}
}

func (_c *MockWithdrawalRepository_FindByOutBizNo_Call) Run(run func(ctx context.Context, outBizNo string)) *MockWithdrawalRepository_FindByOutBizNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWithdrawalRepository_FindByOutBizNo_Call) Return(_a0 model.WithdrawalModel, _a1 error) *MockWithdrawalRepository_FindByOutBizNo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawalRepository_FindByOutBizNo_Call) RunAndReturn(run func(context.Context, string) (model.WithdrawalModel, error)) *MockWithdrawalRepository_FindByOutBizNo_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, withdrawal
func (_m *MockWithdrawalRepository) Save(ctx context.Context, withdrawal model.WithdrawalModel) (model.WithdrawalModel, error) {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.WithdrawalModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.WithdrawalModel) (model.WithdrawalModel, error)); ok {
		return rf(ctx, withdrawal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.WithdrawalModel) model.WithdrawalModel); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Get(0).(model.WithdrawalModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.WithdrawalModel) error); ok {
		r1 = rf(ctx, withdrawal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawalRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWithdrawalRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal model.WithdrawalModel
func (_e *MockWithdrawalRepository_Expecter) Save(ctx interface{}, withdrawal interface{}) *MockWithdrawalRepository_Save_Call {
	return &MockWithdrawalRepository_Save_Call{Call: _e.mock.On("Save", ctx, withdrawal)}
}

func (_c *MockWithdrawalRepository_Save_Call) Run(run func(ctx context.Context, withdrawal model.WithdrawalModel)) *MockWithdrawalRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WithdrawalModel))
	})
	return _c
}

func (_c *MockWithdrawalRepository_Save_Call) Return(_a0 model.WithdrawalModel, _a1 error) *MockWithdrawalRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawalRepository_Save_Call) RunAndReturn(run func(context.Context, model.WithdrawalModel) (model.WithdrawalModel, error)) *MockWithdrawalRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, withdrawal
func (_m *MockWithdrawalRepository) Update(ctx context.Context, withdrawal model.WithdrawalModel) (model.WithdrawalModel, error) {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.WithdrawalModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.WithdrawalModel) (model.WithdrawalModel, error)); ok {
		return rf(ctx, withdrawal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.WithdrawalModel) model.WithdrawalModel); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Get(0).(model.WithdrawalModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.WithdrawalModel) error); ok {
		r1 = rf(ctx, withdrawal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawalRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWithdrawalRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal model.WithdrawalModel
func (_e *MockWithdrawalRepository_Expecter) Update(ctx interface{}, withdrawal interface{}) *MockWithdrawalRepository_Update_Call {
	return &MockWithdrawalRepository_Update_Call{Call: _e.mock.On("Update", ctx, withdrawal)}
}

func (_c *MockWithdrawalRepository_Update_Call) Run(run func(ctx context.Context, withdrawal model.WithdrawalModel)) *MockWithdrawalRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WithdrawalModel))
	})
	return _c
}

func (_c *MockWithdrawalRepository_Update_Call) Return(_a0 model.WithdrawalModel, _a1 error) *MockWithdrawalRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawalRepository_Update_Call) RunAndReturn(run func(context.Context, model.WithdrawalModel) (model.WithdrawalModel, error)) *MockWithdrawalRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdrawalRepository creates a new instance of MockWithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdrawalRepository {
	mock := &MockWithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
