// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/payment/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepository) FindByID(ctx context.Context, id uint64) (model.PaymentModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.PaymentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.PaymentModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.PaymentModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.PaymentModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPaymentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockPaymentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPaymentRepository_FindByID_Call {
	return &MockPaymentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPaymentRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockPaymentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockPaymentRepository_FindByID_Call) Return(_a0 model.PaymentModel, _a1 error) *MockPaymentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.PaymentModel, error)) *MockPaymentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOutTradeNo provides a mock function with given fields: ctx, outTradeNo
func (_m *MockPaymentRepository) FindByOutTradeNo(ctx context.Context, outTradeNo string) (model.PaymentModel, error) {
	ret := _m.Called(ctx, outTradeNo)

	if len(ret) == 0 {
		panic("no return value specified for FindByOutTradeNo")
	}

	var r0 model.PaymentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PaymentModel, error)); ok {
		return rf(ctx, outTradeNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PaymentModel); ok {
		r0 = rf(ctx, outTradeNo)
	} else {
		r0 = ret.Get(0).(model.PaymentModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, outTradeNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_FindByOutTradeNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOutTradeNo'
type MockPaymentRepository_FindByOutTradeNo_Call struct {
	*mock.Call
}

// FindByOutTradeNo is a helper method to define mock.On call
//   - ctx context.Context
//   - outTradeNo string
func (_e *MockPaymentRepository_Expecter) FindByOutTradeNo(ctx interface{}, outTradeNo interface{}) *MockPaymentRepository_FindByOutTradeNo_Call {
	return &MockPaymentRepository_FindByOutTradeNo_Call{Call: _e.mock.On("FindByOutTradeNo", ctx, outTradeNo)}
}

func (_c *MockPaymentRepository_FindByOutTradeNo_Call) Run(run func(ctx context.Context, outTradeNo string)) *MockPaymentRepository_FindByOutTradeNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_FindByOutTradeNo_Call) Return(_a0 model.PaymentModel, _a1 error) *MockPaymentRepository_FindByOutTradeNo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_FindByOutTradeNo_Call) RunAndReturn(run func(context.Context, string) (model.PaymentModel, error)) *MockPaymentRepository_FindByOutTradeNo_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) Save(ctx context.Context, payment model.PaymentModel) (model.PaymentModel, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.PaymentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentModel) (model.PaymentModel, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentModel) model.PaymentModel); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(model.PaymentModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PaymentModel) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPaymentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.PaymentModel
func (_e *MockPaymentRepository_Expecter) Save(ctx interface{}, payment interface{}) *MockPaymentRepository_Save_Call {
	return &MockPaymentRepository_Save_Call{Call: _e.mock.On("Save", ctx, payment)}
}

func (_c *MockPaymentRepository_Save_Call) Run(run func(ctx context.Context, payment model.PaymentModel)) *MockPaymentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PaymentModel))
	})
	return _c
}

func (_c *MockPaymentRepository_Save_Call) Return(_a0 model.PaymentModel, _a1 error) *MockPaymentRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Save_Call) RunAndReturn(run func(context.Context, model.PaymentModel) (model.PaymentModel, error)) *MockPaymentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) Update(ctx context.Context, payment model.PaymentModel) (model.PaymentModel, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.PaymentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentModel) (model.PaymentModel, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentModel) model.PaymentModel); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(model.PaymentModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PaymentModel) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPaymentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.PaymentModel
func (_e *MockPaymentRepository_Expecter) Update(ctx interface{}, payment interface{}) *MockPaymentRepository_Update_Call {
	return &MockPaymentRepository_Update_Call{Call: _e.mock.On("Update", ctx, payment)}
}

func (_c *MockPaymentRepository_Update_Call) Run(run func(ctx context.Context, payment model.PaymentModel)) *MockPaymentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PaymentModel))
	})
	return _c
}

func (_c *MockPaymentRepository_Update_Call) Return(_a0 model.PaymentModel, _a1 error) *MockPaymentRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Update_Call) RunAndReturn(run func(context.Context, model.PaymentModel) (model.PaymentModel, error)) *MockPaymentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
