// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/ledger/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLedgerUnitOfWorkFactory is an autogenerated mock type for the LedgerUnitOfWorkFactory type
type MockLedgerUnitOfWorkFactory struct {
	mock.Mock
}

type MockLedgerUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerUnitOfWorkFactory) EXPECT() *MockLedgerUnitOfWorkFactory_Expecter {
	return &MockLedgerUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockLedgerUnitOfWorkFactory) Begin(ctx context.Context) (ports.LedgerUnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 ports.LedgerUnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ports.LedgerUnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ports.LedgerUnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.LedgerUnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerUnitOfWorkFactory_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockLedgerUnitOfWorkFactory_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLedgerUnitOfWorkFactory_Expecter) Begin(ctx interface{}) *MockLedgerUnitOfWorkFactory_Begin_Call {
	return &MockLedgerUnitOfWorkFactory_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockLedgerUnitOfWorkFactory_Begin_Call) Run(run func(ctx context.Context)) *MockLedgerUnitOfWorkFactory_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLedgerUnitOfWorkFactory_Begin_Call) Return(_a0 ports.LedgerUnitOfWork, _a1 error) *MockLedgerUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerUnitOfWorkFactory_Begin_Call) RunAndReturn(run func(context.Context) (ports.LedgerUnitOfWork, error)) *MockLedgerUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerUnitOfWorkFactory creates a new instance of MockLedgerUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerUnitOfWorkFactory {
	mock := &MockLedgerUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
