// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuctionReadPort is an autogenerated mock type for the AuctionReadPort type
type MockAuctionReadPort struct {
	mock.Mock
}

type MockAuctionReadPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionReadPort) EXPECT() *MockAuctionReadPort_Expecter {
	return &MockAuctionReadPort_Expecter{mock: &_m.Mock}
}

// FindBidderIDByBidID provides a mock function with given fields: ctx, bidID
func (_m *MockAuctionReadPort) FindBidderIDByBidID(ctx context.Context, bidID uint64) (uint64, bool, error) {
	ret := _m.Called(ctx, bidID)

	if len(ret) == 0 {
		panic("no return value specified for FindBidderIDByBidID")
	}

	var r0 uint64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, bool, error)); ok {
		return rf(ctx, bidID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, bidID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) bool); ok {
		r1 = rf(ctx, bidID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, bidID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuctionReadPort_FindBidderIDByBidID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBidderIDByBidID'
type MockAuctionReadPort_FindBidderIDByBidID_Call struct {
	*mock.Call
}

// FindBidderIDByBidID is a helper method to define mock.On call
//   - ctx context.Context
//   - bidID uint64
func (_e *MockAuctionReadPort_Expecter) FindBidderIDByBidID(ctx interface{}, bidID interface{}) *MockAuctionReadPort_FindBidderIDByBidID_Call {
	return &MockAuctionReadPort_FindBidderIDByBidID_Call{Call: _e.mock.On("FindBidderIDByBidID", ctx, bidID)}
}

func (_c *MockAuctionReadPort_FindBidderIDByBidID_Call) Run(run func(ctx context.Context, bidID uint64)) *MockAuctionReadPort_FindBidderIDByBidID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuctionReadPort_FindBidderIDByBidID_Call) Return(_a0 uint64, _a1 bool, _a2 error) *MockAuctionReadPort_FindBidderIDByBidID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuctionReadPort_FindBidderIDByBidID_Call) RunAndReturn(run func(context.Context, uint64) (uint64, bool, error)) *MockAuctionReadPort_FindBidderIDByBidID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPreviousHighestBidderID provides a mock function with given fields: ctx, auctionID, currentBidderID
func (_m *MockAuctionReadPort) FindPreviousHighestBidderID(ctx context.Context, auctionID uint64, currentBidderID uint64) (uint64, bool, error) {
	ret := _m.Called(ctx, auctionID, currentBidderID)

	if len(ret) == 0 {
		panic("no return value specified for FindPreviousHighestBidderID")
	}

	var r0 uint64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (uint64, bool, error)); ok {
		return rf(ctx, auctionID, currentBidderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) uint64); ok {
		r0 = rf(ctx, auctionID, currentBidderID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) bool); ok {
		r1 = rf(ctx, auctionID, currentBidderID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = rf(ctx, auctionID, currentBidderID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuctionReadPort_FindPreviousHighestBidderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPreviousHighestBidderID'
type MockAuctionReadPort_FindPreviousHighestBidderID_Call struct {
	*mock.Call
}

// FindPreviousHighestBidderID is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
//   - currentBidderID uint64
func (_e *MockAuctionReadPort_Expecter) FindPreviousHighestBidderID(ctx interface{}, auctionID interface{}, currentBidderID interface{}) *MockAuctionReadPort_FindPreviousHighestBidderID_Call {
	return &MockAuctionReadPort_FindPreviousHighestBidderID_Call{Call: _e.mock.On("FindPreviousHighestBidderID", ctx, auctionID, currentBidderID)}
}

func (_c *MockAuctionReadPort_FindPreviousHighestBidderID_Call) Run(run func(ctx context.Context, auctionID uint64, currentBidderID uint64)) *MockAuctionReadPort_FindPreviousHighestBidderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockAuctionReadPort_FindPreviousHighestBidderID_Call) Return(_a0 uint64, _a1 bool, _a2 error) *MockAuctionReadPort_FindPreviousHighestBidderID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuctionReadPort_FindPreviousHighestBidderID_Call) RunAndReturn(run func(context.Context, uint64, uint64) (uint64, bool, error)) *MockAuctionReadPort_FindPreviousHighestBidderID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionReadPort creates a new instance of MockAuctionReadPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionReadPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionReadPort {
	mock := &MockAuctionReadPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
