// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/ledger/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLedgerUnitOfWork is an autogenerated mock type for the LedgerUnitOfWork type
type MockLedgerUnitOfWork struct {
	mock.Mock
}

type MockLedgerUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerUnitOfWork) EXPECT() *MockLedgerUnitOfWork_Expecter {
	return &MockLedgerUnitOfWork_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx
func (_m *MockLedgerUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockLedgerUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLedgerUnitOfWork_Expecter) Complete(ctx interface{}) *MockLedgerUnitOfWork_Complete_Call {
	return &MockLedgerUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockLedgerUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockLedgerUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLedgerUnitOfWork_Complete_Call) Return(_a0 error) *MockLedgerUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockLedgerUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// LedgerRepository provides a mock function with no fields
func (_m *MockLedgerUnitOfWork) LedgerRepository() ports.LedgerRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LedgerRepository")
	}

	var r0 ports.LedgerRepository
	if rf, ok := ret.Get(0).(func() ports.LedgerRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.LedgerRepository)
		}
	}

	return r0
}

// MockLedgerUnitOfWork_LedgerRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LedgerRepository'
type MockLedgerUnitOfWork_LedgerRepository_Call struct {
	*mock.Call
}

// LedgerRepository is a helper method to define mock.On call
func (_e *MockLedgerUnitOfWork_Expecter) LedgerRepository() *MockLedgerUnitOfWork_LedgerRepository_Call {
	return &MockLedgerUnitOfWork_LedgerRepository_Call{Call: _e.mock.On("LedgerRepository")}
}

func (_c *MockLedgerUnitOfWork_LedgerRepository_Call) Run(run func()) *MockLedgerUnitOfWork_LedgerRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLedgerUnitOfWork_LedgerRepository_Call) Return(_a0 ports.LedgerRepository) *MockLedgerUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerUnitOfWork_LedgerRepository_Call) RunAndReturn(run func() ports.LedgerRepository) *MockLedgerUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockLedgerUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockLedgerUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLedgerUnitOfWork_Expecter) Rollback(ctx interface{}) *MockLedgerUnitOfWork_Rollback_Call {
	return &MockLedgerUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockLedgerUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockLedgerUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLedgerUnitOfWork_Rollback_Call) Return(_a0 error) *MockLedgerUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockLedgerUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerUnitOfWork creates a new instance of MockLedgerUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerUnitOfWork {
	mock := &MockLedgerUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
