// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	enum "auction/internal/modules/auction/domain/enum"
	strategy "auction/internal/modules/auction/domain/strategy"

	mock "github.com/stretchr/testify/mock"
)

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// ForMode provides a mock function with given fields: mode
func (_m *MockResolver) ForMode(mode enum.TradingModeEnum) (strategy.TradingStrategy, error) {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for ForMode")
	}

	var r0 strategy.TradingStrategy
	var r1 error
	if rf, ok := ret.Get(0).(func(enum.TradingModeEnum) (strategy.TradingStrategy, error)); ok {
		return rf(mode)
	}
	if rf, ok := ret.Get(0).(func(enum.TradingModeEnum) strategy.TradingStrategy); ok {
		r0 = rf(mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.TradingStrategy)
		}
	}

	if rf, ok := ret.Get(1).(func(enum.TradingModeEnum) error); ok {
		r1 = rf(mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResolver_ForMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForMode'
type MockResolver_ForMode_Call struct {
	*mock.Call
}

// ForMode is a helper method to define mock.On call
//   - mode enum.TradingModeEnum
func (_e *MockResolver_Expecter) ForMode(mode interface{}) *MockResolver_ForMode_Call {
	return &MockResolver_ForMode_Call{Call: _e.mock.On("ForMode", mode)}
}

func (_c *MockResolver_ForMode_Call) Run(run func(mode enum.TradingModeEnum)) *MockResolver_ForMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(enum.TradingModeEnum))
	})
	return _c
}

func (_c *MockResolver_ForMode_Call) Return(_a0 strategy.TradingStrategy, _a1 error) *MockResolver_ForMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResolver_ForMode_Call) RunAndReturn(run func(enum.TradingModeEnum) (strategy.TradingStrategy, error)) *MockResolver_ForMode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
