// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/listing/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockListingUnitOfWorkFactory is an autogenerated mock type for the ListingUnitOfWorkFactory type
type MockListingUnitOfWorkFactory struct {
	mock.Mock
}

type MockListingUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListingUnitOfWorkFactory) EXPECT() *MockListingUnitOfWorkFactory_Expecter {
	return &MockListingUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockListingUnitOfWorkFactory) Begin(ctx context.Context) (ports.ListingUnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 ports.ListingUnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ports.ListingUnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ports.ListingUnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.ListingUnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListingUnitOfWorkFactory_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockListingUnitOfWorkFactory_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListingUnitOfWorkFactory_Expecter) Begin(ctx interface{}) *MockListingUnitOfWorkFactory_Begin_Call {
	return &MockListingUnitOfWorkFactory_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockListingUnitOfWorkFactory_Begin_Call) Run(run func(ctx context.Context)) *MockListingUnitOfWorkFactory_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockListingUnitOfWorkFactory_Begin_Call) Return(_a0 ports.ListingUnitOfWork, _a1 error) *MockListingUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListingUnitOfWorkFactory_Begin_Call) RunAndReturn(run func(context.Context) (ports.ListingUnitOfWork, error)) *MockListingUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListingUnitOfWorkFactory creates a new instance of MockListingUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListingUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListingUnitOfWorkFactory {
	mock := &MockListingUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
