// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/notification/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWatchlistRepository is an autogenerated mock type for the WatchlistRepository type
type MockWatchlistRepository struct {
	mock.Mock
}

type MockWatchlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchlistRepository) EXPECT() *MockWatchlistRepository_Expecter {
	return &MockWatchlistRepository_Expecter{mock: &_m.Mock}
}

// FindWatcherIDsBySpuID provides a mock function with given fields: ctx, spuID
func (_m *MockWatchlistRepository) FindWatcherIDsBySpuID(ctx context.Context, spuID uint64) ([]uint64, error) {
	ret := _m.Called(ctx, spuID)

	if len(ret) == 0 {
		panic("no return value specified for FindWatcherIDsBySpuID")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]uint64, error)); ok {
		return rf(ctx, spuID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []uint64); ok {
		r0 = rf(ctx, spuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, spuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_FindWatcherIDsBySpuID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWatcherIDsBySpuID'
type MockWatchlistRepository_FindWatcherIDsBySpuID_Call struct {
	*mock.Call
}

// FindWatcherIDsBySpuID is a helper method to define mock.On call
//   - ctx context.Context
//   - spuID uint64
func (_e *MockWatchlistRepository_Expecter) FindWatcherIDsBySpuID(ctx interface{}, spuID interface{}) *MockWatchlistRepository_FindWatcherIDsBySpuID_Call {
	return &MockWatchlistRepository_FindWatcherIDsBySpuID_Call{Call: _e.mock.On("FindWatcherIDsBySpuID", ctx, spuID)}
}

func (_c *MockWatchlistRepository_FindWatcherIDsBySpuID_Call) Run(run func(ctx context.Context, spuID uint64)) *MockWatchlistRepository_FindWatcherIDsBySpuID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockWatchlistRepository_FindWatcherIDsBySpuID_Call) Return(_a0 []uint64, _a1 error) *MockWatchlistRepository_FindWatcherIDsBySpuID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_FindWatcherIDsBySpuID_Call) RunAndReturn(run func(context.Context, uint64) ([]uint64, error)) *MockWatchlistRepository_FindWatcherIDsBySpuID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockWatchlistRepository) ListByUser(ctx context.Context, userID uint64, limit int, offset int) ([]model.Watchlist, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) ([]model.Watchlist, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) []model.Watchlist); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Watchlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockWatchlistRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - limit int
//   - offset int
func (_e *MockWatchlistRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockWatchlistRepository_ListByUser_Call {
	return &MockWatchlistRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit, offset)}
}

func (_c *MockWatchlistRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint64, limit int, offset int)) *MockWatchlistRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWatchlistRepository_ListByUser_Call) Return(_a0 []model.Watchlist, _a1 error) *MockWatchlistRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uint64, int, int) ([]model.Watchlist, error)) *MockWatchlistRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, userID, spuID
func (_m *MockWatchlistRepository) Remove(ctx context.Context, userID uint64, spuID uint64) error {
	ret := _m.Called(ctx, userID, spuID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = rf(ctx, userID, spuID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWatchlistRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockWatchlistRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - spuID uint64
func (_e *MockWatchlistRepository_Expecter) Remove(ctx interface{}, userID interface{}, spuID interface{}) *MockWatchlistRepository_Remove_Call {
	return &MockWatchlistRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, userID, spuID)}
}

func (_c *MockWatchlistRepository_Remove_Call) Run(run func(ctx context.Context, userID uint64, spuID uint64)) *MockWatchlistRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockWatchlistRepository_Remove_Call) Return(_a0 error) *MockWatchlistRepository_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWatchlistRepository_Remove_Call) RunAndReturn(run func(context.Context, uint64, uint64) error) *MockWatchlistRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, watchlist
func (_m *MockWatchlistRepository) Save(ctx context.Context, watchlist model.Watchlist) (model.Watchlist, error) {
	ret := _m.Called(ctx, watchlist)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Watchlist) (model.Watchlist, error)); ok {
		return rf(ctx, watchlist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Watchlist) model.Watchlist); ok {
		r0 = rf(ctx, watchlist)
	} else {
		r0 = ret.Get(0).(model.Watchlist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Watchlist) error); ok {
		r1 = rf(ctx, watchlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWatchlistRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWatchlistRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - watchlist model.Watchlist
func (_e *MockWatchlistRepository_Expecter) Save(ctx interface{}, watchlist interface{}) *MockWatchlistRepository_Save_Call {
	return &MockWatchlistRepository_Save_Call{Call: _e.mock.On("Save", ctx, watchlist)}
}

func (_c *MockWatchlistRepository_Save_Call) Run(run func(ctx context.Context, watchlist model.Watchlist)) *MockWatchlistRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Watchlist))
	})
	return _c
}

func (_c *MockWatchlistRepository_Save_Call) Return(_a0 model.Watchlist, _a1 error) *MockWatchlistRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatchlistRepository_Save_Call) RunAndReturn(run func(context.Context, model.Watchlist) (model.Watchlist, error)) *MockWatchlistRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWatchlistRepository creates a new instance of MockWatchlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchlistRepository {
	mock := &MockWatchlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
