// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	envelope "auction/internal/modules/auction/infra/event/envelope"
	messaging "auction/internal/modules/auction/infra/messaging"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventReplayer is an autogenerated mock type for the EventReplayer type
type MockEventReplayer struct {
	mock.Mock
}

type MockEventReplayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventReplayer) EXPECT() *MockEventReplayer_Expecter {
	return &MockEventReplayer_Expecter{mock: &_m.Mock}
}

// ReplayAuction provides a mock function with given fields: ctx, auctionID, filter
func (_m *MockEventReplayer) ReplayAuction(ctx context.Context, auctionID uint64, filter messaging.ReplayFilter) ([]envelope.Envelope, error) {
	ret := _m.Called(ctx, auctionID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ReplayAuction")
	}

	var r0 []envelope.Envelope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, messaging.ReplayFilter) ([]envelope.Envelope, error)); ok {
		return rf(ctx, auctionID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, messaging.ReplayFilter) []envelope.Envelope); ok {
		r0 = rf(ctx, auctionID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]envelope.Envelope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, messaging.ReplayFilter) error); ok {
		r1 = rf(ctx, auctionID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventReplayer_ReplayAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayAuction'
type MockEventReplayer_ReplayAuction_Call struct {
	*mock.Call
}

// ReplayAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
//   - filter messaging.ReplayFilter
func (_e *MockEventReplayer_Expecter) ReplayAuction(ctx interface{}, auctionID interface{}, filter interface{}) *MockEventReplayer_ReplayAuction_Call {
	return &MockEventReplayer_ReplayAuction_Call{Call: _e.mock.On("ReplayAuction", ctx, auctionID, filter)}
}

func (_c *MockEventReplayer_ReplayAuction_Call) Run(run func(ctx context.Context, auctionID uint64, filter messaging.ReplayFilter)) *MockEventReplayer_ReplayAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(messaging.ReplayFilter))
	})
	return _c
}

func (_c *MockEventReplayer_ReplayAuction_Call) Return(_a0 []envelope.Envelope, _a1 error) *MockEventReplayer_ReplayAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventReplayer_ReplayAuction_Call) RunAndReturn(run func(context.Context, uint64, messaging.ReplayFilter) ([]envelope.Envelope, error)) *MockEventReplayer_ReplayAuction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventReplayer creates a new instance of MockEventReplayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventReplayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventReplayer {
	mock := &MockEventReplayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
