// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/payment/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAlipayPort is an autogenerated mock type for the AlipayPort type
type MockAlipayPort struct {
	mock.Mock
}

type MockAlipayPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlipayPort) EXPECT() *MockAlipayPort_Expecter {
	return &MockAlipayPort_Expecter{mock: &_m.Mock}
}

// CreateFaceToFacePayment provides a mock function with given fields: ctx, input
func (_m *MockAlipayPort) CreateFaceToFacePayment(ctx context.Context, input ports.FaceToFaceInput) (ports.FaceToFaceOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateFaceToFacePayment")
	}

	var r0 ports.FaceToFaceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.FaceToFaceInput) (ports.FaceToFaceOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.FaceToFaceInput) ports.FaceToFaceOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(ports.FaceToFaceOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.FaceToFaceInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlipayPort_CreateFaceToFacePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFaceToFacePayment'
type MockAlipayPort_CreateFaceToFacePayment_Call struct {
	*mock.Call
}

// CreateFaceToFacePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.FaceToFaceInput
func (_e *MockAlipayPort_Expecter) CreateFaceToFacePayment(ctx interface{}, input interface{}) *MockAlipayPort_CreateFaceToFacePayment_Call {
	return &MockAlipayPort_CreateFaceToFacePayment_Call{Call: _e.mock.On("CreateFaceToFacePayment", ctx, input)}
}

func (_c *MockAlipayPort_CreateFaceToFacePayment_Call) Run(run func(ctx context.Context, input ports.FaceToFaceInput)) *MockAlipayPort_CreateFaceToFacePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.FaceToFaceInput))
	})
	return _c
}

func (_c *MockAlipayPort_CreateFaceToFacePayment_Call) Return(_a0 ports.FaceToFaceOutput, _a1 error) *MockAlipayPort_CreateFaceToFacePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlipayPort_CreateFaceToFacePayment_Call) RunAndReturn(run func(context.Context, ports.FaceToFaceInput) (ports.FaceToFaceOutput, error)) *MockAlipayPort_CreateFaceToFacePayment_Call {
	_c.Call.Return(run)
	return _c
}

// TransferToAlipayAccount provides a mock function with given fields: ctx, input
func (_m *MockAlipayPort) TransferToAlipayAccount(ctx context.Context, input ports.TransferInput) (ports.TransferOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TransferToAlipayAccount")
	}

	var r0 ports.TransferOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.TransferInput) (ports.TransferOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.TransferInput) ports.TransferOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(ports.TransferOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.TransferInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlipayPort_TransferToAlipayAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferToAlipayAccount'
type MockAlipayPort_TransferToAlipayAccount_Call struct {
	*mock.Call
}

// TransferToAlipayAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.TransferInput
func (_e *MockAlipayPort_Expecter) TransferToAlipayAccount(ctx interface{}, input interface{}) *MockAlipayPort_TransferToAlipayAccount_Call {
	return &MockAlipayPort_TransferToAlipayAccount_Call{Call: _e.mock.On("TransferToAlipayAccount", ctx, input)}
}

func (_c *MockAlipayPort_TransferToAlipayAccount_Call) Run(run func(ctx context.Context, input ports.TransferInput)) *MockAlipayPort_TransferToAlipayAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.TransferInput))
	})
	return _c
}

func (_c *MockAlipayPort_TransferToAlipayAccount_Call) Return(_a0 ports.TransferOutput, _a1 error) *MockAlipayPort_TransferToAlipayAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlipayPort_TransferToAlipayAccount_Call) RunAndReturn(run func(context.Context, ports.TransferInput) (ports.TransferOutput, error)) *MockAlipayPort_TransferToAlipayAccount_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyNotify provides a mock function with given fields: ctx, params
func (_m *MockAlipayPort) VerifyNotify(ctx context.Context, params map[string]string) (ports.NotifyResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for VerifyNotify")
	}

	var r0 ports.NotifyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (ports.NotifyResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) ports.NotifyResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(ports.NotifyResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlipayPort_VerifyNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyNotify'
type MockAlipayPort_VerifyNotify_Call struct {
	*mock.Call
}

// VerifyNotify is a helper method to define mock.On call
//   - ctx context.Context
//   - params map[string]string
func (_e *MockAlipayPort_Expecter) VerifyNotify(ctx interface{}, params interface{}) *MockAlipayPort_VerifyNotify_Call {
	return &MockAlipayPort_VerifyNotify_Call{Call: _e.mock.On("VerifyNotify", ctx, params)}
}

func (_c *MockAlipayPort_VerifyNotify_Call) Run(run func(ctx context.Context, params map[string]string)) *MockAlipayPort_VerifyNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockAlipayPort_VerifyNotify_Call) Return(_a0 ports.NotifyResult, _a1 error) *MockAlipayPort_VerifyNotify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlipayPort_VerifyNotify_Call) RunAndReturn(run func(context.Context, map[string]string) (ports.NotifyResult, error)) *MockAlipayPort_VerifyNotify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlipayPort creates a new instance of MockAlipayPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlipayPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlipayPort {
	mock := &MockAlipayPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
