// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/cristiano-pacheco/go-online-auction/internal/modules/auction/domain/event"
	mock "github.com/stretchr/testify/mock"
)

// MockBidPlacedEventDispatcher is an autogenerated mock type for the BidPlacedEventDispatcher type
type MockBidPlacedEventDispatcher struct {
	mock.Mock
}

type MockBidPlacedEventDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBidPlacedEventDispatcher) EXPECT() *MockBidPlacedEventDispatcher_Expecter {
	return &MockBidPlacedEventDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, _a1
func (_m *MockBidPlacedEventDispatcher) Dispatch(ctx context.Context, _a1 event.BidPlacedEvent) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.BidPlacedEvent) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidPlacedEventDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockBidPlacedEventDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 event.BidPlacedEvent
func (_e *MockBidPlacedEventDispatcher_Expecter) Dispatch(ctx interface{}, _a1 interface{}) *MockBidPlacedEventDispatcher_Dispatch_Call {
	return &MockBidPlacedEventDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, _a1)}
}

func (_c *MockBidPlacedEventDispatcher_Dispatch_Call) Run(run func(ctx context.Context, _a1 event.BidPlacedEvent)) *MockBidPlacedEventDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.BidPlacedEvent))
	})
	return _c
}

func (_c *MockBidPlacedEventDispatcher_Dispatch_Call) Return(_a0 error) *MockBidPlacedEventDispatcher_Dispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidPlacedEventDispatcher_Dispatch_Call) RunAndReturn(run func(context.Context, event.BidPlacedEvent) error) *MockBidPlacedEventDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBidPlacedEventDispatcher creates a new instance of MockBidPlacedEventDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBidPlacedEventDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBidPlacedEventDispatcher {
	mock := &MockBidPlacedEventDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
