// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/listing/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSkuRepository is an autogenerated mock type for the SkuRepository type
type MockSkuRepository struct {
	mock.Mock
}

type MockSkuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkuRepository) EXPECT() *MockSkuRepository_Expecter {
	return &MockSkuRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sku
func (_m *MockSkuRepository) Create(ctx context.Context, sku model.SkuModel) (model.SkuModel, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.SkuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SkuModel) (model.SkuModel, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SkuModel) model.SkuModel); ok {
		r0 = rf(ctx, sku)
	} else {
		r0 = ret.Get(0).(model.SkuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SkuModel) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkuRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSkuRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sku model.SkuModel
func (_e *MockSkuRepository_Expecter) Create(ctx interface{}, sku interface{}) *MockSkuRepository_Create_Call {
	return &MockSkuRepository_Create_Call{Call: _e.mock.On("Create", ctx, sku)}
}

func (_c *MockSkuRepository_Create_Call) Run(run func(ctx context.Context, sku model.SkuModel)) *MockSkuRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SkuModel))
	})
	return _c
}

func (_c *MockSkuRepository_Create_Call) Return(_a0 model.SkuModel, _a1 error) *MockSkuRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkuRepository_Create_Call) RunAndReturn(run func(context.Context, model.SkuModel) (model.SkuModel, error)) *MockSkuRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSkuRepository) FindByID(ctx context.Context, id uint64) (model.SkuModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.SkuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.SkuModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.SkuModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.SkuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkuRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSkuRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockSkuRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSkuRepository_FindByID_Call {
	return &MockSkuRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSkuRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockSkuRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSkuRepository_FindByID_Call) Return(_a0 model.SkuModel, _a1 error) *MockSkuRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkuRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.SkuModel, error)) *MockSkuRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *MockSkuRepository) FindByIDForUpdate(ctx context.Context, id uint64) (model.SkuModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 model.SkuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.SkuModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.SkuModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.SkuModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkuRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockSkuRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockSkuRepository_Expecter) FindByIDForUpdate(ctx interface{}, id interface{}) *MockSkuRepository_FindByIDForUpdate_Call {
	return &MockSkuRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, id)}
}

func (_c *MockSkuRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, id uint64)) *MockSkuRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSkuRepository_FindByIDForUpdate_Call) Return(_a0 model.SkuModel, _a1 error) *MockSkuRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkuRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, uint64) (model.SkuModel, error)) *MockSkuRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySpuID provides a mock function with given fields: ctx, spuID
func (_m *MockSkuRepository) FindBySpuID(ctx context.Context, spuID uint64) ([]model.SkuModel, error) {
	ret := _m.Called(ctx, spuID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySpuID")
	}

	var r0 []model.SkuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.SkuModel, error)); ok {
		return rf(ctx, spuID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.SkuModel); ok {
		r0 = rf(ctx, spuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SkuModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, spuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkuRepository_FindBySpuID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySpuID'
type MockSkuRepository_FindBySpuID_Call struct {
	*mock.Call
}

// FindBySpuID is a helper method to define mock.On call
//   - ctx context.Context
//   - spuID uint64
func (_e *MockSkuRepository_Expecter) FindBySpuID(ctx interface{}, spuID interface{}) *MockSkuRepository_FindBySpuID_Call {
	return &MockSkuRepository_FindBySpuID_Call{Call: _e.mock.On("FindBySpuID", ctx, spuID)}
}

func (_c *MockSkuRepository_FindBySpuID_Call) Run(run func(ctx context.Context, spuID uint64)) *MockSkuRepository_FindBySpuID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSkuRepository_FindBySpuID_Call) Return(_a0 []model.SkuModel, _a1 error) *MockSkuRepository_FindBySpuID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkuRepository_FindBySpuID_Call) RunAndReturn(run func(context.Context, uint64) ([]model.SkuModel, error)) *MockSkuRepository_FindBySpuID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPublishedBySpuIDForUpdate provides a mock function with given fields: ctx, spuID
func (_m *MockSkuRepository) FindPublishedBySpuIDForUpdate(ctx context.Context, spuID uint64) ([]model.SkuModel, error) {
	ret := _m.Called(ctx, spuID)

	if len(ret) == 0 {
		panic("no return value specified for FindPublishedBySpuIDForUpdate")
	}

	var r0 []model.SkuModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.SkuModel, error)); ok {
		return rf(ctx, spuID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.SkuModel); ok {
		r0 = rf(ctx, spuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SkuModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, spuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSkuRepository_FindPublishedBySpuIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPublishedBySpuIDForUpdate'
type MockSkuRepository_FindPublishedBySpuIDForUpdate_Call struct {
	*mock.Call
}

// FindPublishedBySpuIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - spuID uint64
func (_e *MockSkuRepository_Expecter) FindPublishedBySpuIDForUpdate(ctx interface{}, spuID interface{}) *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call {
	return &MockSkuRepository_FindPublishedBySpuIDForUpdate_Call{Call: _e.mock.On("FindPublishedBySpuIDForUpdate", ctx, spuID)}
}

func (_c *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call) Run(run func(ctx context.Context, spuID uint64)) *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call) Return(_a0 []model.SkuModel, _a1 error) *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call) RunAndReturn(run func(context.Context, uint64) ([]model.SkuModel, error)) *MockSkuRepository_FindPublishedBySpuIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, sku
func (_m *MockSkuRepository) Update(ctx context.Context, sku model.SkuModel) error {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SkuModel) error); ok {
		r0 = rf(ctx, sku)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSkuRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSkuRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sku model.SkuModel
func (_e *MockSkuRepository_Expecter) Update(ctx interface{}, sku interface{}) *MockSkuRepository_Update_Call {
	return &MockSkuRepository_Update_Call{Call: _e.mock.On("Update", ctx, sku)}
}

func (_c *MockSkuRepository_Update_Call) Run(run func(ctx context.Context, sku model.SkuModel)) *MockSkuRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SkuModel))
	})
	return _c
}

func (_c *MockSkuRepository_Update_Call) Return(_a0 error) *MockSkuRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSkuRepository_Update_Call) RunAndReturn(run func(context.Context, model.SkuModel) error) *MockSkuRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSkuRepository creates a new instance of MockSkuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkuRepository {
	mock := &MockSkuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
