// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/auction/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuctionUnitOfWork is an autogenerated mock type for the AuctionUnitOfWork type
type MockAuctionUnitOfWork struct {
	mock.Mock
}

type MockAuctionUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionUnitOfWork) EXPECT() *MockAuctionUnitOfWork_Expecter {
	return &MockAuctionUnitOfWork_Expecter{mock: &_m.Mock}
}

// AuctionRepository provides a mock function with no fields
func (_m *MockAuctionUnitOfWork) AuctionRepository() ports.AuctionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuctionRepository")
	}

	var r0 ports.AuctionRepository
	if rf, ok := ret.Get(0).(func() ports.AuctionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.AuctionRepository)
		}
	}

	return r0
}

// MockAuctionUnitOfWork_AuctionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuctionRepository'
type MockAuctionUnitOfWork_AuctionRepository_Call struct {
	*mock.Call
}

// AuctionRepository is a helper method to define mock.On call
func (_e *MockAuctionUnitOfWork_Expecter) AuctionRepository() *MockAuctionUnitOfWork_AuctionRepository_Call {
	return &MockAuctionUnitOfWork_AuctionRepository_Call{Call: _e.mock.On("AuctionRepository")}
}

func (_c *MockAuctionUnitOfWork_AuctionRepository_Call) Run(run func()) *MockAuctionUnitOfWork_AuctionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionUnitOfWork_AuctionRepository_Call) Return(_a0 ports.AuctionRepository) *MockAuctionUnitOfWork_AuctionRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionUnitOfWork_AuctionRepository_Call) RunAndReturn(run func() ports.AuctionRepository) *MockAuctionUnitOfWork_AuctionRepository_Call {
	_c.Call.Return(run)
	return _c
}

// BidRepository provides a mock function with no fields
func (_m *MockAuctionUnitOfWork) BidRepository() ports.BidRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BidRepository")
	}

	var r0 ports.BidRepository
	if rf, ok := ret.Get(0).(func() ports.BidRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.BidRepository)
		}
	}

	return r0
}

// MockAuctionUnitOfWork_BidRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BidRepository'
type MockAuctionUnitOfWork_BidRepository_Call struct {
	*mock.Call
}

// BidRepository is a helper method to define mock.On call
func (_e *MockAuctionUnitOfWork_Expecter) BidRepository() *MockAuctionUnitOfWork_BidRepository_Call {
	return &MockAuctionUnitOfWork_BidRepository_Call{Call: _e.mock.On("BidRepository")}
}

func (_c *MockAuctionUnitOfWork_BidRepository_Call) Run(run func()) *MockAuctionUnitOfWork_BidRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionUnitOfWork_BidRepository_Call) Return(_a0 ports.BidRepository) *MockAuctionUnitOfWork_BidRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionUnitOfWork_BidRepository_Call) RunAndReturn(run func() ports.BidRepository) *MockAuctionUnitOfWork_BidRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx
func (_m *MockAuctionUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuctionUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockAuctionUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuctionUnitOfWork_Expecter) Complete(ctx interface{}) *MockAuctionUnitOfWork_Complete_Call {
	return &MockAuctionUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockAuctionUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockAuctionUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuctionUnitOfWork_Complete_Call) Return(_a0 error) *MockAuctionUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockAuctionUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// OutboxRepository provides a mock function with no fields
func (_m *MockAuctionUnitOfWork) OutboxRepository() ports.OutboxRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutboxRepository")
	}

	var r0 ports.OutboxRepository
	if rf, ok := ret.Get(0).(func() ports.OutboxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.OutboxRepository)
		}
	}

	return r0
}

// MockAuctionUnitOfWork_OutboxRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutboxRepository'
type MockAuctionUnitOfWork_OutboxRepository_Call struct {
	*mock.Call
}

// OutboxRepository is a helper method to define mock.On call
func (_e *MockAuctionUnitOfWork_Expecter) OutboxRepository() *MockAuctionUnitOfWork_OutboxRepository_Call {
	return &MockAuctionUnitOfWork_OutboxRepository_Call{Call: _e.mock.On("OutboxRepository")}
}

func (_c *MockAuctionUnitOfWork_OutboxRepository_Call) Run(run func()) *MockAuctionUnitOfWork_OutboxRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionUnitOfWork_OutboxRepository_Call) Return(_a0 ports.OutboxRepository) *MockAuctionUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionUnitOfWork_OutboxRepository_Call) RunAndReturn(run func() ports.OutboxRepository) *MockAuctionUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockAuctionUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuctionUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockAuctionUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuctionUnitOfWork_Expecter) Rollback(ctx interface{}) *MockAuctionUnitOfWork_Rollback_Call {
	return &MockAuctionUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockAuctionUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockAuctionUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuctionUnitOfWork_Rollback_Call) Return(_a0 error) *MockAuctionUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockAuctionUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionUnitOfWork creates a new instance of MockAuctionUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionUnitOfWork {
	mock := &MockAuctionUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
