// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/cristiano-pacheco/go-online-auction/internal/modules/auction/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockAuctionUnitOfWorkFactory is an autogenerated mock type for the AuctionUnitOfWorkFactory type
type MockAuctionUnitOfWorkFactory struct {
	mock.Mock
}

type MockAuctionUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionUnitOfWorkFactory) EXPECT() *MockAuctionUnitOfWorkFactory_Expecter {
	return &MockAuctionUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockAuctionUnitOfWorkFactory) Begin(ctx context.Context) (ports.AuctionUnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 ports.AuctionUnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ports.AuctionUnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ports.AuctionUnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.AuctionUnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionUnitOfWorkFactory_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockAuctionUnitOfWorkFactory_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuctionUnitOfWorkFactory_Expecter) Begin(ctx interface{}) *MockAuctionUnitOfWorkFactory_Begin_Call {
	return &MockAuctionUnitOfWorkFactory_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockAuctionUnitOfWorkFactory_Begin_Call) Run(run func(ctx context.Context)) *MockAuctionUnitOfWorkFactory_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuctionUnitOfWorkFactory_Begin_Call) Return(_a0 ports.AuctionUnitOfWork, _a1 error) *MockAuctionUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionUnitOfWorkFactory_Begin_Call) RunAndReturn(run func(context.Context) (ports.AuctionUnitOfWork, error)) *MockAuctionUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionUnitOfWorkFactory creates a new instance of MockAuctionUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionUnitOfWorkFactory {
	mock := &MockAuctionUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
