// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/notification/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPreferenceRepository is an autogenerated mock type for the PreferenceRepository type
type MockPreferenceRepository struct {
	mock.Mock
}

type MockPreferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreferenceRepository) EXPECT() *MockPreferenceRepository_Expecter {
	return &MockPreferenceRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *MockPreferenceRepository) Get(ctx context.Context, userID uint64) (model.NotificationPreferenceModel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.NotificationPreferenceModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.NotificationPreferenceModel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.NotificationPreferenceModel); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.NotificationPreferenceModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPreferenceRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPreferenceRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockPreferenceRepository_Expecter) Get(ctx interface{}, userID interface{}) *MockPreferenceRepository_Get_Call {
	return &MockPreferenceRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *MockPreferenceRepository_Get_Call) Run(run func(ctx context.Context, userID uint64)) *MockPreferenceRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockPreferenceRepository_Get_Call) Return(_a0 model.NotificationPreferenceModel, _a1 error) *MockPreferenceRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPreferenceRepository_Get_Call) RunAndReturn(run func(context.Context, uint64) (model.NotificationPreferenceModel, error)) *MockPreferenceRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, preference
func (_m *MockPreferenceRepository) Upsert(ctx context.Context, preference model.NotificationPreferenceModel) (model.NotificationPreferenceModel, error) {
	ret := _m.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 model.NotificationPreferenceModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationPreferenceModel) (model.NotificationPreferenceModel, error)); ok {
		return rf(ctx, preference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationPreferenceModel) model.NotificationPreferenceModel); ok {
		r0 = rf(ctx, preference)
	} else {
		r0 = ret.Get(0).(model.NotificationPreferenceModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NotificationPreferenceModel) error); ok {
		r1 = rf(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPreferenceRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockPreferenceRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - preference model.NotificationPreferenceModel
func (_e *MockPreferenceRepository_Expecter) Upsert(ctx interface{}, preference interface{}) *MockPreferenceRepository_Upsert_Call {
	return &MockPreferenceRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, preference)}
}

func (_c *MockPreferenceRepository_Upsert_Call) Run(run func(ctx context.Context, preference model.NotificationPreferenceModel)) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.NotificationPreferenceModel))
	})
	return _c
}

func (_c *MockPreferenceRepository_Upsert_Call) Return(_a0 model.NotificationPreferenceModel, _a1 error) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPreferenceRepository_Upsert_Call) RunAndReturn(run func(context.Context, model.NotificationPreferenceModel) (model.NotificationPreferenceModel, error)) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPreferenceRepository creates a new instance of MockPreferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreferenceRepository {
	mock := &MockPreferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
