// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMoneyView is an autogenerated mock type for the MoneyView type
type MockMoneyView struct {
	mock.Mock
}

type MockMoneyView_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMoneyView) EXPECT() *MockMoneyView_Expecter {
	return &MockMoneyView_Expecter{mock: &_m.Mock}
}

// AmountInCents provides a mock function with no fields
func (_m *MockMoneyView) AmountInCents() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AmountInCents")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockMoneyView_AmountInCents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AmountInCents'
type MockMoneyView_AmountInCents_Call struct {
	*mock.Call
}

// AmountInCents is a helper method to define mock.On call
func (_e *MockMoneyView_Expecter) AmountInCents() *MockMoneyView_AmountInCents_Call {
	return &MockMoneyView_AmountInCents_Call{Call: _e.mock.On("AmountInCents")}
}

func (_c *MockMoneyView_AmountInCents_Call) Run(run func()) *MockMoneyView_AmountInCents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMoneyView_AmountInCents_Call) Return(_a0 uint64) *MockMoneyView_AmountInCents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMoneyView_AmountInCents_Call) RunAndReturn(run func() uint64) *MockMoneyView_AmountInCents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMoneyView creates a new instance of MockMoneyView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMoneyView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMoneyView {
	mock := &MockMoneyView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
