// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/listing/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CountChildren provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) CountChildren(ctx context.Context, id uint64) (uint64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountChildren")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CountChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountChildren'
type MockCategoryRepository_CountChildren_Call struct {
	*mock.Call
}

// CountChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockCategoryRepository_Expecter) CountChildren(ctx interface{}, id interface{}) *MockCategoryRepository_CountChildren_Call {
	return &MockCategoryRepository_CountChildren_Call{Call: _e.mock.On("CountChildren", ctx, id)}
}

func (_c *MockCategoryRepository_CountChildren_Call) Run(run func(ctx context.Context, id uint64)) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_CountChildren_Call) Return(_a0 uint64, _a1 error) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CountChildren_Call) RunAndReturn(run func(context.Context, uint64) (uint64, error)) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Return(run)
	return _c
}

// CountSpusByCategory provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) CountSpusByCategory(ctx context.Context, id uint64) (uint64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountSpusByCategory")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CountSpusByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSpusByCategory'
type MockCategoryRepository_CountSpusByCategory_Call struct {
	*mock.Call
}

// CountSpusByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockCategoryRepository_Expecter) CountSpusByCategory(ctx interface{}, id interface{}) *MockCategoryRepository_CountSpusByCategory_Call {
	return &MockCategoryRepository_CountSpusByCategory_Call{Call: _e.mock.On("CountSpusByCategory", ctx, id)}
}

func (_c *MockCategoryRepository_CountSpusByCategory_Call) Run(run func(ctx context.Context, id uint64)) *MockCategoryRepository_CountSpusByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_CountSpusByCategory_Call) Return(_a0 uint64, _a1 error) *MockCategoryRepository_CountSpusByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CountSpusByCategory_Call) RunAndReturn(run func(context.Context, uint64) (uint64, error)) *MockCategoryRepository_CountSpusByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) Create(ctx context.Context, category model.CategoryModel) (model.CategoryModel, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.CategoryModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CategoryModel) (model.CategoryModel, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CategoryModel) model.CategoryModel); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Get(0).(model.CategoryModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CategoryModel) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category model.CategoryModel
func (_e *MockCategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(ctx context.Context, category model.CategoryModel)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CategoryModel))
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(_a0 model.CategoryModel, _a1 error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, model.CategoryModel) (model.CategoryModel, error)) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) Delete(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id uint64)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(_a0 error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, uint64) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) FindByID(ctx context.Context, id uint64) (model.CategoryModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.CategoryModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.CategoryModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.CategoryModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CategoryModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockCategoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCategoryRepository_FindByID_Call {
	return &MockCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCategoryRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) Return(_a0 model.CategoryModel, _a1 error) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.CategoryModel, error)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, parentID
func (_m *MockCategoryRepository) List(ctx context.Context, parentID *uint64) ([]model.CategoryModel, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.CategoryModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uint64) ([]model.CategoryModel, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uint64) []model.CategoryModel); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CategoryModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uint64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *uint64
func (_e *MockCategoryRepository_Expecter) List(ctx interface{}, parentID interface{}) *MockCategoryRepository_List_Call {
	return &MockCategoryRepository_List_Call{Call: _e.mock.On("List", ctx, parentID)}
}

func (_c *MockCategoryRepository_List_Call) Run(run func(ctx context.Context, parentID *uint64)) *MockCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_List_Call) Return(_a0 []model.CategoryModel, _a1 error) *MockCategoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_List_Call) RunAndReturn(run func(context.Context, *uint64) ([]model.CategoryModel, error)) *MockCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockCategoryRepository) ListAll(ctx context.Context) ([]model.CategoryModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []model.CategoryModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.CategoryModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.CategoryModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CategoryModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockCategoryRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryRepository_Expecter) ListAll(ctx interface{}) *MockCategoryRepository_ListAll_Call {
	return &MockCategoryRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockCategoryRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockCategoryRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCategoryRepository_ListAll_Call) Return(_a0 []model.CategoryModel, _a1 error) *MockCategoryRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_ListAll_Call) RunAndReturn(run func(context.Context) ([]model.CategoryModel, error)) *MockCategoryRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListDescendants provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) ListDescendants(ctx context.Context, id uint64) ([]model.CategoryModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListDescendants")
	}

	var r0 []model.CategoryModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.CategoryModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.CategoryModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CategoryModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_ListDescendants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDescendants'
type MockCategoryRepository_ListDescendants_Call struct {
	*mock.Call
}

// ListDescendants is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockCategoryRepository_Expecter) ListDescendants(ctx interface{}, id interface{}) *MockCategoryRepository_ListDescendants_Call {
	return &MockCategoryRepository_ListDescendants_Call{Call: _e.mock.On("ListDescendants", ctx, id)}
}

func (_c *MockCategoryRepository_ListDescendants_Call) Run(run func(ctx context.Context, id uint64)) *MockCategoryRepository_ListDescendants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCategoryRepository_ListDescendants_Call) Return(_a0 []model.CategoryModel, _a1 error) *MockCategoryRepository_ListDescendants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_ListDescendants_Call) RunAndReturn(run func(context.Context, uint64) ([]model.CategoryModel, error)) *MockCategoryRepository_ListDescendants_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) Update(ctx context.Context, category model.CategoryModel) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CategoryModel) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category model.CategoryModel
func (_e *MockCategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(ctx context.Context, category model.CategoryModel)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CategoryModel))
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(_a0 error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, model.CategoryModel) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
