// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/payment/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentUnitOfWorkFactory is an autogenerated mock type for the PaymentUnitOfWorkFactory type
type MockPaymentUnitOfWorkFactory struct {
	mock.Mock
}

type MockPaymentUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentUnitOfWorkFactory) EXPECT() *MockPaymentUnitOfWorkFactory_Expecter {
	return &MockPaymentUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockPaymentUnitOfWorkFactory) Begin(ctx context.Context) (ports.PaymentUnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 ports.PaymentUnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ports.PaymentUnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ports.PaymentUnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.PaymentUnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUnitOfWorkFactory_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockPaymentUnitOfWorkFactory_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentUnitOfWorkFactory_Expecter) Begin(ctx interface{}) *MockPaymentUnitOfWorkFactory_Begin_Call {
	return &MockPaymentUnitOfWorkFactory_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockPaymentUnitOfWorkFactory_Begin_Call) Run(run func(ctx context.Context)) *MockPaymentUnitOfWorkFactory_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentUnitOfWorkFactory_Begin_Call) Return(_a0 ports.PaymentUnitOfWork, _a1 error) *MockPaymentUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUnitOfWorkFactory_Begin_Call) RunAndReturn(run func(context.Context) (ports.PaymentUnitOfWork, error)) *MockPaymentUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentUnitOfWorkFactory creates a new instance of MockPaymentUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentUnitOfWorkFactory {
	mock := &MockPaymentUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
