// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/notification/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) CountUnread(ctx context.Context, userID uint64) (uint64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockNotificationRepository_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) CountUnread(ctx interface{}, userID interface{}) *MockNotificationRepository_CountUnread_Call {
	return &MockNotificationRepository_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockNotificationRepository_CountUnread_Call) Run(run func(ctx context.Context, userID uint64)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) Return(_a0 uint64, _a1 error) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_CountUnread_Call) RunAndReturn(run func(context.Context, uint64) (uint64, error)) *MockNotificationRepository_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, userID
func (_m *MockNotificationRepository) Delete(ctx context.Context, id uint64, userID uint64) (bool, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (bool, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) bool); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotificationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockNotificationRepository_Delete_Call {
	return &MockNotificationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockNotificationRepository_Delete_Call) Run(run func(ctx context.Context, id uint64, userID uint64)) *MockNotificationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) Return(_a0 bool, _a1 error) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_Delete_Call) RunAndReturn(run func(context.Context, uint64, uint64) (bool, error)) *MockNotificationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockNotificationRepository) FindByID(ctx context.Context, id uint64) (model.NotificationModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.NotificationModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.NotificationModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.NotificationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockNotificationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockNotificationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockNotificationRepository_FindByID_Call {
	return &MockNotificationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockNotificationRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockNotificationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepository_FindByID_Call) Return(_a0 model.NotificationModel, _a1 error) *MockNotificationRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.NotificationModel, error)) *MockNotificationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockNotificationRepository) ListByUser(ctx context.Context, userID uint64, limit int, offset int) ([]model.NotificationModel, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) ([]model.NotificationModel, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) []model.NotificationModel); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NotificationModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockNotificationRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_ListByUser_Call {
	return &MockNotificationRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit, offset)}
}

func (_c *MockNotificationRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint64, limit int, offset int)) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_ListByUser_Call) Return(_a0 []model.NotificationModel, _a1 error) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uint64, int, int) ([]model.NotificationModel, error)) *MockNotificationRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnreadByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockNotificationRepository) ListUnreadByUser(ctx context.Context, userID uint64, limit int, offset int) ([]model.NotificationModel, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUnreadByUser")
	}

	var r0 []model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) ([]model.NotificationModel, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) []model.NotificationModel); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NotificationModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_ListUnreadByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnreadByUser'
type MockNotificationRepository_ListUnreadByUser_Call struct {
	*mock.Call
}

// ListUnreadByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - limit int
//   - offset int
func (_e *MockNotificationRepository_Expecter) ListUnreadByUser(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockNotificationRepository_ListUnreadByUser_Call {
	return &MockNotificationRepository_ListUnreadByUser_Call{Call: _e.mock.On("ListUnreadByUser", ctx, userID, limit, offset)}
}

func (_c *MockNotificationRepository_ListUnreadByUser_Call) Run(run func(ctx context.Context, userID uint64, limit int, offset int)) *MockNotificationRepository_ListUnreadByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_ListUnreadByUser_Call) Return(_a0 []model.NotificationModel, _a1 error) *MockNotificationRepository_ListUnreadByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_ListUnreadByUser_Call) RunAndReturn(run func(context.Context, uint64, int, int) ([]model.NotificationModel, error)) *MockNotificationRepository_ListUnreadByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) MarkAllRead(ctx context.Context, userID uint64) (uint64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotificationRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *MockNotificationRepository_MarkAllRead_Call {
	return &MockNotificationRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockNotificationRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID uint64)) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAllRead_Call) Return(_a0 uint64, _a1 error) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_MarkAllRead_Call) RunAndReturn(run func(context.Context, uint64) (uint64, error)) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *MockNotificationRepository) MarkRead(ctx context.Context, id uint64, userID uint64) (bool, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (bool, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) bool); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - userID uint64
func (_e *MockNotificationRepository_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}) *MockNotificationRepository_MarkRead_Call {
	return &MockNotificationRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID)}
}

func (_c *MockNotificationRepository_MarkRead_Call) Run(run func(ctx context.Context, id uint64, userID uint64)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) Return(_a0 bool, _a1 error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) RunAndReturn(run func(context.Context, uint64, uint64) (bool, error)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, notification
func (_m *MockNotificationRepository) Save(ctx context.Context, notification model.NotificationModel) (model.NotificationModel, bool, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.NotificationModel
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) (model.NotificationModel, bool, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) model.NotificationModel); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Get(0).(model.NotificationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NotificationModel) bool); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.NotificationModel) error); ok {
		r2 = rf(ctx, notification)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockNotificationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockNotificationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - notification model.NotificationModel
func (_e *MockNotificationRepository_Expecter) Save(ctx interface{}, notification interface{}) *MockNotificationRepository_Save_Call {
	return &MockNotificationRepository_Save_Call{Call: _e.mock.On("Save", ctx, notification)}
}

func (_c *MockNotificationRepository_Save_Call) Run(run func(ctx context.Context, notification model.NotificationModel)) *MockNotificationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.NotificationModel))
	})
	return _c
}

func (_c *MockNotificationRepository_Save_Call) Return(_a0 model.NotificationModel, _a1 bool, _a2 error) *MockNotificationRepository_Save_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockNotificationRepository_Save_Call) RunAndReturn(run func(context.Context, model.NotificationModel) (model.NotificationModel, bool, error)) *MockNotificationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
