// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "auction/internal/modules/users/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, token model.RefreshTokenModel) (model.RefreshTokenModel, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.RefreshTokenModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RefreshTokenModel) (model.RefreshTokenModel, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RefreshTokenModel) model.RefreshTokenModel); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(model.RefreshTokenModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RefreshTokenModel) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.RefreshTokenModel
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token model.RefreshTokenModel)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RefreshTokenModel))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 model.RefreshTokenModel, _a1 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, model.RefreshTokenModel) (model.RefreshTokenModel, error)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (model.RefreshTokenModel, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 model.RefreshTokenModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.RefreshTokenModel, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RefreshTokenModel); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.RefreshTokenModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type MockRefreshTokenRepository_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_FindByTokenHash_Call {
	return &MockRefreshTokenRepository_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) Return(_a0 model.RefreshTokenModel, _a1 error) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) RunAndReturn(run func(context.Context, string) (model.RefreshTokenModel, error)) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID uint64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockRefreshTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	return &MockRefreshTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uint64)) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(context.Context, uint64) error) *MockRefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Update(ctx context.Context, token model.RefreshTokenModel) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RefreshTokenModel) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRefreshTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.RefreshTokenModel
func (_e *MockRefreshTokenRepository_Expecter) Update(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Update_Call {
	return &MockRefreshTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Update_Call) Run(run func(ctx context.Context, token model.RefreshTokenModel)) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RefreshTokenModel))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) Return(_a0 error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) RunAndReturn(run func(context.Context, model.RefreshTokenModel) error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
