// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	enum "github.com/cristiano-pacheco/go-online-auction/internal/modules/auction/domain/enum"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cristiano-pacheco/go-online-auction/internal/modules/auction/domain/model"
)

// MockAuctionRepository is an autogenerated mock type for the AuctionRepository type
type MockAuctionRepository struct {
	mock.Mock
}

type MockAuctionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionRepository) EXPECT() *MockAuctionRepository_Expecter {
	return &MockAuctionRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, state
func (_m *MockAuctionRepository) Count(ctx context.Context, state *enum.AuctionStateEnum) (uint64, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *enum.AuctionStateEnum) (uint64, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *enum.AuctionStateEnum) uint64); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *enum.AuctionStateEnum) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAuctionRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - state *enum.AuctionStateEnum
func (_e *MockAuctionRepository_Expecter) Count(ctx interface{}, state interface{}) *MockAuctionRepository_Count_Call {
	return &MockAuctionRepository_Count_Call{Call: _e.mock.On("Count", ctx, state)}
}

func (_c *MockAuctionRepository_Count_Call) Run(run func(ctx context.Context, state *enum.AuctionStateEnum)) *MockAuctionRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*enum.AuctionStateEnum))
	})
	return _c
}

func (_c *MockAuctionRepository_Count_Call) Return(_a0 uint64, _a1 error) *MockAuctionRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionRepository_Count_Call) RunAndReturn(run func(context.Context, *enum.AuctionStateEnum) (uint64, error)) *MockAuctionRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, auction
func (_m *MockAuctionRepository) Create(ctx context.Context, auction model.AuctionModel) (model.AuctionModel, error) {
	ret := _m.Called(ctx, auction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.AuctionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuctionModel) (model.AuctionModel, error)); ok {
		return rf(ctx, auction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AuctionModel) model.AuctionModel); ok {
		r0 = rf(ctx, auction)
	} else {
		r0 = ret.Get(0).(model.AuctionModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AuctionModel) error); ok {
		r1 = rf(ctx, auction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuctionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auction model.AuctionModel
func (_e *MockAuctionRepository_Expecter) Create(ctx interface{}, auction interface{}) *MockAuctionRepository_Create_Call {
	return &MockAuctionRepository_Create_Call{Call: _e.mock.On("Create", ctx, auction)}
}

func (_c *MockAuctionRepository_Create_Call) Run(run func(ctx context.Context, auction model.AuctionModel)) *MockAuctionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AuctionModel))
	})
	return _c
}

func (_c *MockAuctionRepository_Create_Call) Return(_a0 model.AuctionModel, _a1 error) *MockAuctionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionRepository_Create_Call) RunAndReturn(run func(context.Context, model.AuctionModel) (model.AuctionModel, error)) *MockAuctionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginated provides a mock function with given fields: ctx, state, limit, offset
func (_m *MockAuctionRepository) FindAllPaginated(ctx context.Context, state *enum.AuctionStateEnum, limit int, offset int) ([]model.AuctionModel, error) {
	ret := _m.Called(ctx, state, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []model.AuctionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *enum.AuctionStateEnum, int, int) ([]model.AuctionModel, error)); ok {
		return rf(ctx, state, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *enum.AuctionStateEnum, int, int) []model.AuctionModel); ok {
		r0 = rf(ctx, state, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuctionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *enum.AuctionStateEnum, int, int) error); ok {
		r1 = rf(ctx, state, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionRepository_FindAllPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginated'
type MockAuctionRepository_FindAllPaginated_Call struct {
	*mock.Call
}

// FindAllPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - state *enum.AuctionStateEnum
//   - limit int
//   - offset int
func (_e *MockAuctionRepository_Expecter) FindAllPaginated(ctx interface{}, state interface{}, limit interface{}, offset interface{}) *MockAuctionRepository_FindAllPaginated_Call {
	return &MockAuctionRepository_FindAllPaginated_Call{Call: _e.mock.On("FindAllPaginated", ctx, state, limit, offset)}
}

func (_c *MockAuctionRepository_FindAllPaginated_Call) Run(run func(ctx context.Context, state *enum.AuctionStateEnum, limit int, offset int)) *MockAuctionRepository_FindAllPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*enum.AuctionStateEnum), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAuctionRepository_FindAllPaginated_Call) Return(_a0 []model.AuctionModel, _a1 error) *MockAuctionRepository_FindAllPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionRepository_FindAllPaginated_Call) RunAndReturn(run func(context.Context, *enum.AuctionStateEnum, int, int) ([]model.AuctionModel, error)) *MockAuctionRepository_FindAllPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAuctionRepository) FindByID(ctx context.Context, id uint64) (model.AuctionModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.AuctionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.AuctionModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.AuctionModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AuctionModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAuctionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockAuctionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockAuctionRepository_FindByID_Call {
	return &MockAuctionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAuctionRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockAuctionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuctionRepository_FindByID_Call) Return(_a0 model.AuctionModel, _a1 error) *MockAuctionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.AuctionModel, error)) *MockAuctionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *MockAuctionRepository) FindByIDForUpdate(ctx context.Context, id uint64) (model.AuctionModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 model.AuctionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.AuctionModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.AuctionModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AuctionModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockAuctionRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockAuctionRepository_Expecter) FindByIDForUpdate(ctx interface{}, id interface{}) *MockAuctionRepository_FindByIDForUpdate_Call {
	return &MockAuctionRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, id)}
}

func (_c *MockAuctionRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, id uint64)) *MockAuctionRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuctionRepository_FindByIDForUpdate_Call) Return(_a0 model.AuctionModel, _a1 error) *MockAuctionRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, uint64) (model.AuctionModel, error)) *MockAuctionRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, auction
func (_m *MockAuctionRepository) Update(ctx context.Context, auction model.AuctionModel) error {
	ret := _m.Called(ctx, auction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuctionModel) error); ok {
		r0 = rf(ctx, auction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuctionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAuctionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - auction model.AuctionModel
func (_e *MockAuctionRepository_Expecter) Update(ctx interface{}, auction interface{}) *MockAuctionRepository_Update_Call {
	return &MockAuctionRepository_Update_Call{Call: _e.mock.On("Update", ctx, auction)}
}

func (_c *MockAuctionRepository_Update_Call) Run(run func(ctx context.Context, auction model.AuctionModel)) *MockAuctionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AuctionModel))
	})
	return _c
}

func (_c *MockAuctionRepository_Update_Call) Return(_a0 error) *MockAuctionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionRepository_Update_Call) RunAndReturn(run func(context.Context, model.AuctionModel) error) *MockAuctionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionRepository creates a new instance of MockAuctionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionRepository {
	mock := &MockAuctionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
