// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/auction/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBidCommandPublisher is an autogenerated mock type for the BidCommandPublisher type
type MockBidCommandPublisher struct {
	mock.Mock
}

type MockBidCommandPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBidCommandPublisher) EXPECT() *MockBidCommandPublisher_Expecter {
	return &MockBidCommandPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, cmd
func (_m *MockBidCommandPublisher) Publish(ctx context.Context, cmd ports.BidCommand) (ports.BidCommandAck, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 ports.BidCommandAck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.BidCommand) (ports.BidCommandAck, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.BidCommand) ports.BidCommandAck); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(ports.BidCommandAck)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.BidCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidCommandPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBidCommandPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd ports.BidCommand
func (_e *MockBidCommandPublisher_Expecter) Publish(ctx interface{}, cmd interface{}) *MockBidCommandPublisher_Publish_Call {
	return &MockBidCommandPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, cmd)}
}

func (_c *MockBidCommandPublisher_Publish_Call) Run(run func(ctx context.Context, cmd ports.BidCommand)) *MockBidCommandPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.BidCommand))
	})
	return _c
}

func (_c *MockBidCommandPublisher_Publish_Call) Return(_a0 ports.BidCommandAck, _a1 error) *MockBidCommandPublisher_Publish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidCommandPublisher_Publish_Call) RunAndReturn(run func(context.Context, ports.BidCommand) (ports.BidCommandAck, error)) *MockBidCommandPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBidCommandPublisher creates a new instance of MockBidCommandPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBidCommandPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBidCommandPublisher {
	mock := &MockBidCommandPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
