// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/listing/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockListingUnitOfWork is an autogenerated mock type for the ListingUnitOfWork type
type MockListingUnitOfWork struct {
	mock.Mock
}

type MockListingUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListingUnitOfWork) EXPECT() *MockListingUnitOfWork_Expecter {
	return &MockListingUnitOfWork_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx
func (_m *MockListingUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListingUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockListingUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListingUnitOfWork_Expecter) Complete(ctx interface{}) *MockListingUnitOfWork_Complete_Call {
	return &MockListingUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockListingUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockListingUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockListingUnitOfWork_Complete_Call) Return(_a0 error) *MockListingUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockListingUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// OutboxRepository provides a mock function with no fields
func (_m *MockListingUnitOfWork) OutboxRepository() ports.ListingOutboxRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutboxRepository")
	}

	var r0 ports.ListingOutboxRepository
	if rf, ok := ret.Get(0).(func() ports.ListingOutboxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.ListingOutboxRepository)
		}
	}

	return r0
}

// MockListingUnitOfWork_OutboxRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutboxRepository'
type MockListingUnitOfWork_OutboxRepository_Call struct {
	*mock.Call
}

// OutboxRepository is a helper method to define mock.On call
func (_e *MockListingUnitOfWork_Expecter) OutboxRepository() *MockListingUnitOfWork_OutboxRepository_Call {
	return &MockListingUnitOfWork_OutboxRepository_Call{Call: _e.mock.On("OutboxRepository")}
}

func (_c *MockListingUnitOfWork_OutboxRepository_Call) Run(run func()) *MockListingUnitOfWork_OutboxRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListingUnitOfWork_OutboxRepository_Call) Return(_a0 ports.ListingOutboxRepository) *MockListingUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingUnitOfWork_OutboxRepository_Call) RunAndReturn(run func() ports.ListingOutboxRepository) *MockListingUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockListingUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListingUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockListingUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListingUnitOfWork_Expecter) Rollback(ctx interface{}) *MockListingUnitOfWork_Rollback_Call {
	return &MockListingUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockListingUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockListingUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockListingUnitOfWork_Rollback_Call) Return(_a0 error) *MockListingUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockListingUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SkuRepository provides a mock function with no fields
func (_m *MockListingUnitOfWork) SkuRepository() ports.SkuRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SkuRepository")
	}

	var r0 ports.SkuRepository
	if rf, ok := ret.Get(0).(func() ports.SkuRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SkuRepository)
		}
	}

	return r0
}

// MockListingUnitOfWork_SkuRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkuRepository'
type MockListingUnitOfWork_SkuRepository_Call struct {
	*mock.Call
}

// SkuRepository is a helper method to define mock.On call
func (_e *MockListingUnitOfWork_Expecter) SkuRepository() *MockListingUnitOfWork_SkuRepository_Call {
	return &MockListingUnitOfWork_SkuRepository_Call{Call: _e.mock.On("SkuRepository")}
}

func (_c *MockListingUnitOfWork_SkuRepository_Call) Run(run func()) *MockListingUnitOfWork_SkuRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListingUnitOfWork_SkuRepository_Call) Return(_a0 ports.SkuRepository) *MockListingUnitOfWork_SkuRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingUnitOfWork_SkuRepository_Call) RunAndReturn(run func() ports.SkuRepository) *MockListingUnitOfWork_SkuRepository_Call {
	_c.Call.Return(run)
	return _c
}

// SpuRepository provides a mock function with no fields
func (_m *MockListingUnitOfWork) SpuRepository() ports.SpuRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SpuRepository")
	}

	var r0 ports.SpuRepository
	if rf, ok := ret.Get(0).(func() ports.SpuRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SpuRepository)
		}
	}

	return r0
}

// MockListingUnitOfWork_SpuRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpuRepository'
type MockListingUnitOfWork_SpuRepository_Call struct {
	*mock.Call
}

// SpuRepository is a helper method to define mock.On call
func (_e *MockListingUnitOfWork_Expecter) SpuRepository() *MockListingUnitOfWork_SpuRepository_Call {
	return &MockListingUnitOfWork_SpuRepository_Call{Call: _e.mock.On("SpuRepository")}
}

func (_c *MockListingUnitOfWork_SpuRepository_Call) Run(run func()) *MockListingUnitOfWork_SpuRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListingUnitOfWork_SpuRepository_Call) Return(_a0 ports.SpuRepository) *MockListingUnitOfWork_SpuRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListingUnitOfWork_SpuRepository_Call) RunAndReturn(run func() ports.SpuRepository) *MockListingUnitOfWork_SpuRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListingUnitOfWork creates a new instance of MockListingUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListingUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListingUnitOfWork {
	mock := &MockListingUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
