// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	ports "auction/internal/modules/deposit/ports"
	ledgerports "auction/internal/modules/ledger/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDepositUnitOfWork is an autogenerated mock type for the DepositUnitOfWork type
type MockDepositUnitOfWork struct {
	mock.Mock
}

type MockDepositUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDepositUnitOfWork) EXPECT() *MockDepositUnitOfWork_Expecter {
	return &MockDepositUnitOfWork_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx
func (_m *MockDepositUnitOfWork) Complete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepositUnitOfWork_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockDepositUnitOfWork_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDepositUnitOfWork_Expecter) Complete(ctx interface{}) *MockDepositUnitOfWork_Complete_Call {
	return &MockDepositUnitOfWork_Complete_Call{Call: _e.mock.On("Complete", ctx)}
}

func (_c *MockDepositUnitOfWork_Complete_Call) Run(run func(ctx context.Context)) *MockDepositUnitOfWork_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDepositUnitOfWork_Complete_Call) Return(_a0 error) *MockDepositUnitOfWork_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositUnitOfWork_Complete_Call) RunAndReturn(run func(context.Context) error) *MockDepositUnitOfWork_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// DepositRepository provides a mock function with no fields
func (_m *MockDepositUnitOfWork) DepositRepository() ports.DepositRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DepositRepository")
	}

	var r0 ports.DepositRepository
	if rf, ok := ret.Get(0).(func() ports.DepositRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.DepositRepository)
		}
	}

	return r0
}

// MockDepositUnitOfWork_DepositRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepositRepository'
type MockDepositUnitOfWork_DepositRepository_Call struct {
	*mock.Call
}

// DepositRepository is a helper method to define mock.On call
func (_e *MockDepositUnitOfWork_Expecter) DepositRepository() *MockDepositUnitOfWork_DepositRepository_Call {
	return &MockDepositUnitOfWork_DepositRepository_Call{Call: _e.mock.On("DepositRepository")}
}

func (_c *MockDepositUnitOfWork_DepositRepository_Call) Run(run func()) *MockDepositUnitOfWork_DepositRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDepositUnitOfWork_DepositRepository_Call) Return(_a0 ports.DepositRepository) *MockDepositUnitOfWork_DepositRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositUnitOfWork_DepositRepository_Call) RunAndReturn(run func() ports.DepositRepository) *MockDepositUnitOfWork_DepositRepository_Call {
	_c.Call.Return(run)
	return _c
}

// LedgerRepository provides a mock function with no fields
func (_m *MockDepositUnitOfWork) LedgerRepository() ledgerports.LedgerRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LedgerRepository")
	}

	var r0 ledgerports.LedgerRepository
	if rf, ok := ret.Get(0).(func() ledgerports.LedgerRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ledgerports.LedgerRepository)
		}
	}

	return r0
}

// MockDepositUnitOfWork_LedgerRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LedgerRepository'
type MockDepositUnitOfWork_LedgerRepository_Call struct {
	*mock.Call
}

// LedgerRepository is a helper method to define mock.On call
func (_e *MockDepositUnitOfWork_Expecter) LedgerRepository() *MockDepositUnitOfWork_LedgerRepository_Call {
	return &MockDepositUnitOfWork_LedgerRepository_Call{Call: _e.mock.On("LedgerRepository")}
}

func (_c *MockDepositUnitOfWork_LedgerRepository_Call) Run(run func()) *MockDepositUnitOfWork_LedgerRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDepositUnitOfWork_LedgerRepository_Call) Return(_a0 ledgerports.LedgerRepository) *MockDepositUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositUnitOfWork_LedgerRepository_Call) RunAndReturn(run func() ledgerports.LedgerRepository) *MockDepositUnitOfWork_LedgerRepository_Call {
	_c.Call.Return(run)
	return _c
}

// OutboxRepository provides a mock function with no fields
func (_m *MockDepositUnitOfWork) OutboxRepository() ports.DepositOutboxRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutboxRepository")
	}

	var r0 ports.DepositOutboxRepository
	if rf, ok := ret.Get(0).(func() ports.DepositOutboxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.DepositOutboxRepository)
		}
	}

	return r0
}

// MockDepositUnitOfWork_OutboxRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutboxRepository'
type MockDepositUnitOfWork_OutboxRepository_Call struct {
	*mock.Call
}

// OutboxRepository is a helper method to define mock.On call
func (_e *MockDepositUnitOfWork_Expecter) OutboxRepository() *MockDepositUnitOfWork_OutboxRepository_Call {
	return &MockDepositUnitOfWork_OutboxRepository_Call{Call: _e.mock.On("OutboxRepository")}
}

func (_c *MockDepositUnitOfWork_OutboxRepository_Call) Run(run func()) *MockDepositUnitOfWork_OutboxRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDepositUnitOfWork_OutboxRepository_Call) Return(_a0 ports.DepositOutboxRepository) *MockDepositUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositUnitOfWork_OutboxRepository_Call) RunAndReturn(run func() ports.DepositOutboxRepository) *MockDepositUnitOfWork_OutboxRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockDepositUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepositUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockDepositUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDepositUnitOfWork_Expecter) Rollback(ctx interface{}) *MockDepositUnitOfWork_Rollback_Call {
	return &MockDepositUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockDepositUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockDepositUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDepositUnitOfWork_Rollback_Call) Return(_a0 error) *MockDepositUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockDepositUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDepositUnitOfWork creates a new instance of MockDepositUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDepositUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDepositUnitOfWork {
	mock := &MockDepositUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
