// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	strategy "auction/internal/modules/auction/domain/strategy"

	mock "github.com/stretchr/testify/mock"
)

// MockBidView is an autogenerated mock type for the BidView type
type MockBidView struct {
	mock.Mock
}

type MockBidView_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBidView) EXPECT() *MockBidView_Expecter {
	return &MockBidView_Expecter{mock: &_m.Mock}
}

// Amount provides a mock function with no fields
func (_m *MockBidView) Amount() strategy.MoneyView {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Amount")
	}

	var r0 strategy.MoneyView
	if rf, ok := ret.Get(0).(func() strategy.MoneyView); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.MoneyView)
		}
	}

	return r0
}

// MockBidView_Amount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Amount'
type MockBidView_Amount_Call struct {
	*mock.Call
}

// Amount is a helper method to define mock.On call
func (_e *MockBidView_Expecter) Amount() *MockBidView_Amount_Call {
	return &MockBidView_Amount_Call{Call: _e.mock.On("Amount")}
}

func (_c *MockBidView_Amount_Call) Run(run func()) *MockBidView_Amount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidView_Amount_Call) Return(_a0 strategy.MoneyView) *MockBidView_Amount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidView_Amount_Call) RunAndReturn(run func() strategy.MoneyView) *MockBidView_Amount_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockBidView) ID() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockBidView_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBidView_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBidView_Expecter) ID() *MockBidView_ID_Call {
	return &MockBidView_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBidView_ID_Call) Run(run func()) *MockBidView_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidView_ID_Call) Return(_a0 uint64) *MockBidView_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidView_ID_Call) RunAndReturn(run func() uint64) *MockBidView_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MaxAmount provides a mock function with no fields
func (_m *MockBidView) MaxAmount() strategy.MoneyView {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxAmount")
	}

	var r0 strategy.MoneyView
	if rf, ok := ret.Get(0).(func() strategy.MoneyView); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategy.MoneyView)
		}
	}

	return r0
}

// MockBidView_MaxAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxAmount'
type MockBidView_MaxAmount_Call struct {
	*mock.Call
}

// MaxAmount is a helper method to define mock.On call
func (_e *MockBidView_Expecter) MaxAmount() *MockBidView_MaxAmount_Call {
	return &MockBidView_MaxAmount_Call{Call: _e.mock.On("MaxAmount")}
}

func (_c *MockBidView_MaxAmount_Call) Run(run func()) *MockBidView_MaxAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidView_MaxAmount_Call) Return(_a0 strategy.MoneyView) *MockBidView_MaxAmount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidView_MaxAmount_Call) RunAndReturn(run func() strategy.MoneyView) *MockBidView_MaxAmount_Call {
	_c.Call.Return(run)
	return _c
}

// UserID provides a mock function with no fields
func (_m *MockBidView) UserID() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserID")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockBidView_UserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserID'
type MockBidView_UserID_Call struct {
	*mock.Call
}

// UserID is a helper method to define mock.On call
func (_e *MockBidView_Expecter) UserID() *MockBidView_UserID_Call {
	return &MockBidView_UserID_Call{Call: _e.mock.On("UserID")}
}

func (_c *MockBidView_UserID_Call) Run(run func()) *MockBidView_UserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidView_UserID_Call) Return(_a0 uint64) *MockBidView_UserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidView_UserID_Call) RunAndReturn(run func() uint64) *MockBidView_UserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBidView creates a new instance of MockBidView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBidView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBidView {
	mock := &MockBidView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
