// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockRequestSigner is an autogenerated mock type for the RequestSigner type
type MockRequestSigner struct {
	mock.Mock
}

type MockRequestSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestSigner) EXPECT() *MockRequestSigner_Expecter {
	return &MockRequestSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function with given fields: request
func (_m *MockRequestSigner) Sign(request *http.Request) {
	_m.Called(request)
}

// MockRequestSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockRequestSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - request *http.Request
func (_e *MockRequestSigner_Expecter) Sign(request interface{}) *MockRequestSigner_Sign_Call {
	return &MockRequestSigner_Sign_Call{Call: _e.mock.On("Sign", request)}
}

func (_c *MockRequestSigner_Sign_Call) Run(run func(request *http.Request)) *MockRequestSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockRequestSigner_Sign_Call) Return() *MockRequestSigner_Sign_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestSigner_Sign_Call) RunAndReturn(run func(*http.Request)) *MockRequestSigner_Sign_Call {
	_c.Run(run)
	return _c
}

// NewMockRequestSigner creates a new instance of MockRequestSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestSigner {
	mock := &MockRequestSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
