// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	enum "auction/internal/modules/auction/domain/enum"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAuctionView is an autogenerated mock type for the AuctionView type
type MockAuctionView struct {
	mock.Mock
}

type MockAuctionView_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionView) EXPECT() *MockAuctionView_Expecter {
	return &MockAuctionView_Expecter{mock: &_m.Mock}
}

// AntiSnipeEnabled provides a mock function with no fields
func (_m *MockAuctionView) AntiSnipeEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AntiSnipeEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuctionView_AntiSnipeEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AntiSnipeEnabled'
type MockAuctionView_AntiSnipeEnabled_Call struct {
	*mock.Call
}

// AntiSnipeEnabled is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) AntiSnipeEnabled() *MockAuctionView_AntiSnipeEnabled_Call {
	return &MockAuctionView_AntiSnipeEnabled_Call{Call: _e.mock.On("AntiSnipeEnabled")}
}

func (_c *MockAuctionView_AntiSnipeEnabled_Call) Run(run func()) *MockAuctionView_AntiSnipeEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_AntiSnipeEnabled_Call) Return(_a0 bool) *MockAuctionView_AntiSnipeEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_AntiSnipeEnabled_Call) RunAndReturn(run func() bool) *MockAuctionView_AntiSnipeEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentPrice provides a mock function with no fields
func (_m *MockAuctionView) CurrentPrice() *uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentPrice")
	}

	var r0 *uint64
	if rf, ok := ret.Get(0).(func() *uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	return r0
}

// MockAuctionView_CurrentPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPrice'
type MockAuctionView_CurrentPrice_Call struct {
	*mock.Call
}

// CurrentPrice is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) CurrentPrice() *MockAuctionView_CurrentPrice_Call {
	return &MockAuctionView_CurrentPrice_Call{Call: _e.mock.On("CurrentPrice")}
}

func (_c *MockAuctionView_CurrentPrice_Call) Run(run func()) *MockAuctionView_CurrentPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_CurrentPrice_Call) Return(_a0 *uint64) *MockAuctionView_CurrentPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_CurrentPrice_Call) RunAndReturn(run func() *uint64) *MockAuctionView_CurrentPrice_Call {
	_c.Call.Return(run)
	return _c
}

// EndTime provides a mock function with no fields
func (_m *MockAuctionView) EndTime() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EndTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockAuctionView_EndTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTime'
type MockAuctionView_EndTime_Call struct {
	*mock.Call
}

// EndTime is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) EndTime() *MockAuctionView_EndTime_Call {
	return &MockAuctionView_EndTime_Call{Call: _e.mock.On("EndTime")}
}

func (_c *MockAuctionView_EndTime_Call) Run(run func()) *MockAuctionView_EndTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_EndTime_Call) Return(_a0 time.Time) *MockAuctionView_EndTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_EndTime_Call) RunAndReturn(run func() time.Time) *MockAuctionView_EndTime_Call {
	_c.Call.Return(run)
	return _c
}

// ExtensionWindowSec provides a mock function with no fields
func (_m *MockAuctionView) ExtensionWindowSec() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtensionWindowSec")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockAuctionView_ExtensionWindowSec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtensionWindowSec'
type MockAuctionView_ExtensionWindowSec_Call struct {
	*mock.Call
}

// ExtensionWindowSec is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) ExtensionWindowSec() *MockAuctionView_ExtensionWindowSec_Call {
	return &MockAuctionView_ExtensionWindowSec_Call{Call: _e.mock.On("ExtensionWindowSec")}
}

func (_c *MockAuctionView_ExtensionWindowSec_Call) Run(run func()) *MockAuctionView_ExtensionWindowSec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_ExtensionWindowSec_Call) Return(_a0 int64) *MockAuctionView_ExtensionWindowSec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_ExtensionWindowSec_Call) RunAndReturn(run func() int64) *MockAuctionView_ExtensionWindowSec_Call {
	_c.Call.Return(run)
	return _c
}

// HighestBidAmount provides a mock function with no fields
func (_m *MockAuctionView) HighestBidAmount() *uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HighestBidAmount")
	}

	var r0 *uint64
	if rf, ok := ret.Get(0).(func() *uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	return r0
}

// MockAuctionView_HighestBidAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HighestBidAmount'
type MockAuctionView_HighestBidAmount_Call struct {
	*mock.Call
}

// HighestBidAmount is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) HighestBidAmount() *MockAuctionView_HighestBidAmount_Call {
	return &MockAuctionView_HighestBidAmount_Call{Call: _e.mock.On("HighestBidAmount")}
}

func (_c *MockAuctionView_HighestBidAmount_Call) Run(run func()) *MockAuctionView_HighestBidAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_HighestBidAmount_Call) Return(_a0 *uint64) *MockAuctionView_HighestBidAmount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_HighestBidAmount_Call) RunAndReturn(run func() *uint64) *MockAuctionView_HighestBidAmount_Call {
	_c.Call.Return(run)
	return _c
}

// PriceStep provides a mock function with no fields
func (_m *MockAuctionView) PriceStep() *uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PriceStep")
	}

	var r0 *uint64
	if rf, ok := ret.Get(0).(func() *uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	return r0
}

// MockAuctionView_PriceStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PriceStep'
type MockAuctionView_PriceStep_Call struct {
	*mock.Call
}

// PriceStep is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) PriceStep() *MockAuctionView_PriceStep_Call {
	return &MockAuctionView_PriceStep_Call{Call: _e.mock.On("PriceStep")}
}

func (_c *MockAuctionView_PriceStep_Call) Run(run func()) *MockAuctionView_PriceStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_PriceStep_Call) Return(_a0 *uint64) *MockAuctionView_PriceStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_PriceStep_Call) RunAndReturn(run func() *uint64) *MockAuctionView_PriceStep_Call {
	_c.Call.Return(run)
	return _c
}

// ReservePrice provides a mock function with no fields
func (_m *MockAuctionView) ReservePrice() *uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReservePrice")
	}

	var r0 *uint64
	if rf, ok := ret.Get(0).(func() *uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	return r0
}

// MockAuctionView_ReservePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReservePrice'
type MockAuctionView_ReservePrice_Call struct {
	*mock.Call
}

// ReservePrice is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) ReservePrice() *MockAuctionView_ReservePrice_Call {
	return &MockAuctionView_ReservePrice_Call{Call: _e.mock.On("ReservePrice")}
}

func (_c *MockAuctionView_ReservePrice_Call) Run(run func()) *MockAuctionView_ReservePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_ReservePrice_Call) Return(_a0 *uint64) *MockAuctionView_ReservePrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_ReservePrice_Call) RunAndReturn(run func() *uint64) *MockAuctionView_ReservePrice_Call {
	_c.Call.Return(run)
	return _c
}

// StartTime provides a mock function with no fields
func (_m *MockAuctionView) StartTime() *time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartTime")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// MockAuctionView_StartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTime'
type MockAuctionView_StartTime_Call struct {
	*mock.Call
}

// StartTime is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) StartTime() *MockAuctionView_StartTime_Call {
	return &MockAuctionView_StartTime_Call{Call: _e.mock.On("StartTime")}
}

func (_c *MockAuctionView_StartTime_Call) Run(run func()) *MockAuctionView_StartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_StartTime_Call) Return(_a0 *time.Time) *MockAuctionView_StartTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_StartTime_Call) RunAndReturn(run func() *time.Time) *MockAuctionView_StartTime_Call {
	_c.Call.Return(run)
	return _c
}

// StartingPrice provides a mock function with no fields
func (_m *MockAuctionView) StartingPrice() *uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartingPrice")
	}

	var r0 *uint64
	if rf, ok := ret.Get(0).(func() *uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	return r0
}

// MockAuctionView_StartingPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartingPrice'
type MockAuctionView_StartingPrice_Call struct {
	*mock.Call
}

// StartingPrice is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) StartingPrice() *MockAuctionView_StartingPrice_Call {
	return &MockAuctionView_StartingPrice_Call{Call: _e.mock.On("StartingPrice")}
}

func (_c *MockAuctionView_StartingPrice_Call) Run(run func()) *MockAuctionView_StartingPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_StartingPrice_Call) Return(_a0 *uint64) *MockAuctionView_StartingPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_StartingPrice_Call) RunAndReturn(run func() *uint64) *MockAuctionView_StartingPrice_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockAuctionView) State() enum.AuctionStateEnum {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 enum.AuctionStateEnum
	if rf, ok := ret.Get(0).(func() enum.AuctionStateEnum); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(enum.AuctionStateEnum)
	}

	return r0
}

// MockAuctionView_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockAuctionView_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) State() *MockAuctionView_State_Call {
	return &MockAuctionView_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockAuctionView_State_Call) Run(run func()) *MockAuctionView_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_State_Call) Return(_a0 enum.AuctionStateEnum) *MockAuctionView_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_State_Call) RunAndReturn(run func() enum.AuctionStateEnum) *MockAuctionView_State_Call {
	_c.Call.Return(run)
	return _c
}

// TradingMode provides a mock function with no fields
func (_m *MockAuctionView) TradingMode() enum.TradingModeEnum {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TradingMode")
	}

	var r0 enum.TradingModeEnum
	if rf, ok := ret.Get(0).(func() enum.TradingModeEnum); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(enum.TradingModeEnum)
	}

	return r0
}

// MockAuctionView_TradingMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TradingMode'
type MockAuctionView_TradingMode_Call struct {
	*mock.Call
}

// TradingMode is a helper method to define mock.On call
func (_e *MockAuctionView_Expecter) TradingMode() *MockAuctionView_TradingMode_Call {
	return &MockAuctionView_TradingMode_Call{Call: _e.mock.On("TradingMode")}
}

func (_c *MockAuctionView_TradingMode_Call) Run(run func()) *MockAuctionView_TradingMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuctionView_TradingMode_Call) Return(_a0 enum.TradingModeEnum) *MockAuctionView_TradingMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuctionView_TradingMode_Call) RunAndReturn(run func() enum.TradingModeEnum) *MockAuctionView_TradingMode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionView creates a new instance of MockAuctionView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionView {
	mock := &MockAuctionView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
