// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auctions.sql

package sqlcgen

import (
	"context"
)

const getAuctionDepositConfig = `-- name: GetAuctionDepositConfig :one
SELECT deposit_required, deposit_amount_in_cents
FROM auctions
WHERE id = $1
`

type GetAuctionDepositConfigRow struct {
	DepositRequired      bool
	DepositAmountInCents int64
}

func (q *Queries) GetAuctionDepositConfig(ctx context.Context, id int64) (GetAuctionDepositConfigRow, error) {
	row := q.db.QueryRow(ctx, getAuctionDepositConfig, id)
	var i GetAuctionDepositConfigRow
	err := row.Scan(&i.DepositRequired, &i.DepositAmountInCents)
	return i, err
}

const getAuctionWinner = `-- name: GetAuctionWinner :one
SELECT winner_user_id
FROM auctions
WHERE id = $1
`

func (q *Queries) GetAuctionWinner(ctx context.Context, id int64) (*int64, error) {
	row := q.db.QueryRow(ctx, getAuctionWinner, id)
	var winner_user_id *int64
	err := row.Scan(&winner_user_id)
	return winner_user_id, err
}
