// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposits.sql

package sqlcgen

import (
	"context"
	"time"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (
    user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
`

type CreateDepositParams struct {
	UserID            int64
	AuctionID         int64
	AmountInCents     int64
	Currency          string
	Status            string
	ExternalReference *string
	Reference         *string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.UserID,
		arg.AuctionID,
		arg.AmountInCents,
		arg.Currency,
		arg.Status,
		arg.ExternalReference,
		arg.Reference,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuctionID,
		&i.AmountInCents,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
FROM deposits
WHERE id = $1
`

func (q *Queries) GetDepositByID(ctx context.Context, id int64) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuctionID,
		&i.AmountInCents,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByUserAndAuction = `-- name: GetDepositByUserAndAuction :one
SELECT id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
FROM deposits
WHERE user_id = $1 AND auction_id = $2
`

type GetDepositByUserAndAuctionParams struct {
	UserID    int64
	AuctionID int64
}

func (q *Queries) GetDepositByUserAndAuction(ctx context.Context, arg GetDepositByUserAndAuctionParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByUserAndAuction, arg.UserID, arg.AuctionID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuctionID,
		&i.AmountInCents,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositsByUser = `-- name: ListDepositsByUser :many
SELECT id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
FROM deposits
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListDepositsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListDepositsByUser(ctx context.Context, arg ListDepositsByUserParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuctionID,
			&i.AmountInCents,
			&i.Currency,
			&i.Status,
			&i.ExternalReference,
			&i.Reference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldDepositsByAuction = `-- name: ListHeldDepositsByAuction :many
SELECT id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
FROM deposits
WHERE auction_id = $1 AND status = 'held'
`

func (q *Queries) ListHeldDepositsByAuction(ctx context.Context, auctionID int64) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listHeldDepositsByAuction, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuctionID,
			&i.AmountInCents,
			&i.Currency,
			&i.Status,
			&i.ExternalReference,
			&i.Reference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeposit = `-- name: UpdateDeposit :one
UPDATE deposits
SET user_id = $2, auction_id = $3, amount_in_cents = $4, currency = $5, status = $6,
    external_reference = $7, reference = $8, version = $9, updated_at = $10
WHERE id = $1 AND version = $11
RETURNING id, user_id, auction_id, amount_in_cents, currency, status, external_reference, reference, version, created_at, updated_at
`

type UpdateDepositParams struct {
	ID                int64
	UserID            int64
	AuctionID         int64
	AmountInCents     int64
	Currency          string
	Status            string
	ExternalReference *string
	Reference         *string
	Version           int64
	UpdatedAt         time.Time
	Version_2         int64
}

func (q *Queries) UpdateDeposit(ctx context.Context, arg UpdateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDeposit,
		arg.ID,
		arg.UserID,
		arg.AuctionID,
		arg.AmountInCents,
		arg.Currency,
		arg.Status,
		arg.ExternalReference,
		arg.Reference,
		arg.Version,
		arg.UpdatedAt,
		arg.Version_2,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuctionID,
		&i.AmountInCents,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
