// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Deposit struct {
	ID                int64
	UserID            int64
	AuctionID         int64
	AmountInCents     int64
	Currency          string
	Status            string
	ExternalReference *string
	Reference         *string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type DepositOutbox struct {
	ID            int64
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
	CreatedAt     time.Time
	PublishedAt   *time.Time
}
