// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlcgen

import (
	"context"
	"time"
)

const countCategoryChildren = `-- name: CountCategoryChildren :one
SELECT COUNT(*) FROM categories
WHERE parent_id = $1::BIGINT
`

func (q *Queries) CountCategoryChildren(ctx context.Context, dollar_1 int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryChildren, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpusByCategory = `-- name: CountSpusByCategory :one
SELECT COUNT(*) FROM spus
WHERE category_id = $1
`

func (q *Queries) CountSpusByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSpusByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id, sort_order, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, parent_id, sort_order, version, created_at, updated_at
`

type CreateCategoryParams struct {
	Name      string
	ParentID  *int64
	SortOrder int32
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, parent_id, sort_order, version, created_at, updated_at FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByParent = `-- name: ListCategoriesByParent :many
SELECT id, name, parent_id, sort_order, version, created_at, updated_at FROM categories
WHERE parent_id = $1::BIGINT
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListCategoriesByParent(ctx context.Context, dollar_1 int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByParent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT id, name, parent_id, sort_order, version, created_at, updated_at FROM categories
WHERE parent_id IS NULL
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET name = $1, sort_order = $2, version = $3, updated_at = $4
WHERE id = $5 AND version = $6
`

type UpdateCategoryParams struct {
	Name            string
	SortOrder       int32
	Version         int64
	UpdatedAt       time.Time
	ID              int64
	PreviousVersion int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory,
		arg.Name,
		arg.SortOrder,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.PreviousVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
