// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ListingStatus string

const (
	ListingStatusDraft     ListingStatus = "draft"
	ListingStatusPublished ListingStatus = "published"
	ListingStatusOffShelf  ListingStatus = "off_shelf"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus
	Valid         bool // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type Category struct {
	ID        int64
	Name      string
	ParentID  *int64
	SortOrder int32
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Depth     int32
	Path      string
}

type Sku struct {
	ID           int64
	SpuID        int64
	SpecValues   []byte
	PriceInCents int64
	Quantity     int64
	Status       ListingStatus
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Spu struct {
	ID          int64
	Title       string
	Description string
	CategoryID  int64
	Brand       *string
	Images      []byte
	Status      ListingStatus
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
