// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertListingOutboxEvent = `-- name: InsertListingOutboxEvent :exec
INSERT INTO event_outbox (event_id, event_type, schema_version, subject, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertListingOutboxEventParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertListingOutboxEvent(ctx context.Context, arg InsertListingOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertListingOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Subject,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
