// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sku.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSku = `-- name: CreateSku :one
INSERT INTO skus (spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at
`

type CreateSkuParams struct {
	SpuID        int64
	SpecValues   []byte
	PriceInCents int64
	Quantity     int64
	Status       ListingStatus
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSku(ctx context.Context, arg CreateSkuParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSku,
		arg.SpuID,
		arg.SpecValues,
		arg.PriceInCents,
		arg.Quantity,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.SpecValues,
		&i.PriceInCents,
		&i.Quantity,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkuByID = `-- name: GetSkuByID :one
SELECT id, spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at FROM skus
WHERE id = $1
`

func (q *Queries) GetSkuByID(ctx context.Context, id int64) (Sku, error) {
	row := q.db.QueryRow(ctx, getSkuByID, id)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.SpecValues,
		&i.PriceInCents,
		&i.Quantity,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkuByIDForUpdate = `-- name: GetSkuByIDForUpdate :one
SELECT id, spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at FROM skus
WHERE id = $1
FOR UPDATE NOWAIT
`

func (q *Queries) GetSkuByIDForUpdate(ctx context.Context, id int64) (Sku, error) {
	row := q.db.QueryRow(ctx, getSkuByIDForUpdate, id)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.SpecValues,
		&i.PriceInCents,
		&i.Quantity,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedSkusBySpuIDForUpdate = `-- name: ListPublishedSkusBySpuIDForUpdate :many
SELECT id, spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at FROM skus
WHERE spu_id = $1 AND status = 'published'
ORDER BY id ASC
FOR UPDATE NOWAIT
`

func (q *Queries) ListPublishedSkusBySpuIDForUpdate(ctx context.Context, spuID int64) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listPublishedSkusBySpuIDForUpdate, spuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sku
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.SpuID,
			&i.SpecValues,
			&i.PriceInCents,
			&i.Quantity,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkusBySpuID = `-- name: ListSkusBySpuID :many
SELECT id, spu_id, spec_values, price_in_cents, quantity, status, version, created_at, updated_at FROM skus
WHERE spu_id = $1
ORDER BY id ASC
`

func (q *Queries) ListSkusBySpuID(ctx context.Context, spuID int64) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listSkusBySpuID, spuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sku
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.SpuID,
			&i.SpecValues,
			&i.PriceInCents,
			&i.Quantity,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSku = `-- name: UpdateSku :execrows
UPDATE skus
SET spec_values = $1, price_in_cents = $2, quantity = $3,
    status = $4, version = $5, updated_at = $6
WHERE id = $7 AND version = $8
`

type UpdateSkuParams struct {
	SpecValues      []byte
	PriceInCents    int64
	Quantity        int64
	Status          ListingStatus
	Version         int64
	UpdatedAt       time.Time
	ID              int64
	PreviousVersion int64
}

func (q *Queries) UpdateSku(ctx context.Context, arg UpdateSkuParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSku,
		arg.SpecValues,
		arg.PriceInCents,
		arg.Quantity,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.PreviousVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
