// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	model "auction/internal/modules/deposit/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDepositRepository is an autogenerated mock type for the DepositRepository type
type MockDepositRepository struct {
	mock.Mock
}

type MockDepositRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDepositRepository) EXPECT() *MockDepositRepository_Expecter {
	return &MockDepositRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockDepositRepository) FindByID(ctx context.Context, id uint64) (model.DepositModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.DepositModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.DepositModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.DepositModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockDepositRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockDepositRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockDepositRepository_FindByID_Call {
	return &MockDepositRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockDepositRepository_FindByID_Call) Run(run func(ctx context.Context, id uint64)) *MockDepositRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockDepositRepository_FindByID_Call) Return(_a0 model.DepositModel, _a1 error) *MockDepositRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.DepositModel, error)) *MockDepositRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndAuction provides a mock function with given fields: ctx, userID, auctionID
func (_m *MockDepositRepository) FindByUserAndAuction(ctx context.Context, userID uint64, auctionID uint64) (model.DepositModel, error) {
	ret := _m.Called(ctx, userID, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndAuction")
	}

	var r0 model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (model.DepositModel, error)); ok {
		return rf(ctx, userID, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) model.DepositModel); ok {
		r0 = rf(ctx, userID, auctionID)
	} else {
		r0 = ret.Get(0).(model.DepositModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, userID, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_FindByUserAndAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndAuction'
type MockDepositRepository_FindByUserAndAuction_Call struct {
	*mock.Call
}

// FindByUserAndAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - auctionID uint64
func (_e *MockDepositRepository_Expecter) FindByUserAndAuction(ctx interface{}, userID interface{}, auctionID interface{}) *MockDepositRepository_FindByUserAndAuction_Call {
	return &MockDepositRepository_FindByUserAndAuction_Call{Call: _e.mock.On("FindByUserAndAuction", ctx, userID, auctionID)}
}

func (_c *MockDepositRepository_FindByUserAndAuction_Call) Run(run func(ctx context.Context, userID uint64, auctionID uint64)) *MockDepositRepository_FindByUserAndAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockDepositRepository_FindByUserAndAuction_Call) Return(_a0 model.DepositModel, _a1 error) *MockDepositRepository_FindByUserAndAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_FindByUserAndAuction_Call) RunAndReturn(run func(context.Context, uint64, uint64) (model.DepositModel, error)) *MockDepositRepository_FindByUserAndAuction_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockDepositRepository) ListByUser(ctx context.Context, userID uint64) ([]model.DepositModel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.DepositModel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.DepositModel); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DepositModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockDepositRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockDepositRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockDepositRepository_ListByUser_Call {
	return &MockDepositRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockDepositRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint64)) *MockDepositRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockDepositRepository_ListByUser_Call) Return(_a0 []model.DepositModel, _a1 error) *MockDepositRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uint64) ([]model.DepositModel, error)) *MockDepositRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListHeldByAuction provides a mock function with given fields: ctx, auctionID
func (_m *MockDepositRepository) ListHeldByAuction(ctx context.Context, auctionID uint64) ([]model.DepositModel, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for ListHeldByAuction")
	}

	var r0 []model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.DepositModel, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.DepositModel); ok {
		r0 = rf(ctx, auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DepositModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_ListHeldByAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHeldByAuction'
type MockDepositRepository_ListHeldByAuction_Call struct {
	*mock.Call
}

// ListHeldByAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
func (_e *MockDepositRepository_Expecter) ListHeldByAuction(ctx interface{}, auctionID interface{}) *MockDepositRepository_ListHeldByAuction_Call {
	return &MockDepositRepository_ListHeldByAuction_Call{Call: _e.mock.On("ListHeldByAuction", ctx, auctionID)}
}

func (_c *MockDepositRepository_ListHeldByAuction_Call) Run(run func(ctx context.Context, auctionID uint64)) *MockDepositRepository_ListHeldByAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockDepositRepository_ListHeldByAuction_Call) Return(_a0 []model.DepositModel, _a1 error) *MockDepositRepository_ListHeldByAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_ListHeldByAuction_Call) RunAndReturn(run func(context.Context, uint64) ([]model.DepositModel, error)) *MockDepositRepository_ListHeldByAuction_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, deposit
func (_m *MockDepositRepository) Save(ctx context.Context, deposit model.DepositModel) (model.DepositModel, error) {
	ret := _m.Called(ctx, deposit)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DepositModel) (model.DepositModel, error)); ok {
		return rf(ctx, deposit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DepositModel) model.DepositModel); ok {
		r0 = rf(ctx, deposit)
	} else {
		r0 = ret.Get(0).(model.DepositModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DepositModel) error); ok {
		r1 = rf(ctx, deposit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockDepositRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - deposit model.DepositModel
func (_e *MockDepositRepository_Expecter) Save(ctx interface{}, deposit interface{}) *MockDepositRepository_Save_Call {
	return &MockDepositRepository_Save_Call{Call: _e.mock.On("Save", ctx, deposit)}
}

func (_c *MockDepositRepository_Save_Call) Run(run func(ctx context.Context, deposit model.DepositModel)) *MockDepositRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.DepositModel))
	})
	return _c
}

func (_c *MockDepositRepository_Save_Call) Return(_a0 model.DepositModel, _a1 error) *MockDepositRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_Save_Call) RunAndReturn(run func(context.Context, model.DepositModel) (model.DepositModel, error)) *MockDepositRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, deposit
func (_m *MockDepositRepository) Update(ctx context.Context, deposit model.DepositModel) (model.DepositModel, error) {
	ret := _m.Called(ctx, deposit)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.DepositModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DepositModel) (model.DepositModel, error)); ok {
		return rf(ctx, deposit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DepositModel) model.DepositModel); ok {
		r0 = rf(ctx, deposit)
	} else {
		r0 = ret.Get(0).(model.DepositModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DepositModel) error); ok {
		r1 = rf(ctx, deposit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepositRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDepositRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - deposit model.DepositModel
func (_e *MockDepositRepository_Expecter) Update(ctx interface{}, deposit interface{}) *MockDepositRepository_Update_Call {
	return &MockDepositRepository_Update_Call{Call: _e.mock.On("Update", ctx, deposit)}
}

func (_c *MockDepositRepository_Update_Call) Run(run func(ctx context.Context, deposit model.DepositModel)) *MockDepositRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.DepositModel))
	})
	return _c
}

func (_c *MockDepositRepository_Update_Call) Return(_a0 model.DepositModel, _a1 error) *MockDepositRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepositRepository_Update_Call) RunAndReturn(run func(context.Context, model.DepositModel) (model.DepositModel, error)) *MockDepositRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDepositRepository creates a new instance of MockDepositRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDepositRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDepositRepository {
	mock := &MockDepositRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
