// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDepositGuard is an autogenerated mock type for the DepositGuard type
type MockDepositGuard struct {
	mock.Mock
}

type MockDepositGuard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDepositGuard) EXPECT() *MockDepositGuard_Expecter {
	return &MockDepositGuard_Expecter{mock: &_m.Mock}
}

// EnsureEligible provides a mock function with given fields: ctx, userID, auctionID
func (_m *MockDepositGuard) EnsureEligible(ctx context.Context, userID uint64, auctionID uint64) error {
	ret := _m.Called(ctx, userID, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureEligible")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = rf(ctx, userID, auctionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepositGuard_EnsureEligible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureEligible'
type MockDepositGuard_EnsureEligible_Call struct {
	*mock.Call
}

// EnsureEligible is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - auctionID uint64
func (_e *MockDepositGuard_Expecter) EnsureEligible(ctx interface{}, userID interface{}, auctionID interface{}) *MockDepositGuard_EnsureEligible_Call {
	return &MockDepositGuard_EnsureEligible_Call{Call: _e.mock.On("EnsureEligible", ctx, userID, auctionID)}
}

func (_c *MockDepositGuard_EnsureEligible_Call) Run(run func(ctx context.Context, userID uint64, auctionID uint64)) *MockDepositGuard_EnsureEligible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockDepositGuard_EnsureEligible_Call) Return(_a0 error) *MockDepositGuard_EnsureEligible_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepositGuard_EnsureEligible_Call) RunAndReturn(run func(context.Context, uint64, uint64) error) *MockDepositGuard_EnsureEligible_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDepositGuard creates a new instance of MockDepositGuard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDepositGuard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDepositGuard {
	mock := &MockDepositGuard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
