// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	model "auction/internal/modules/deposit/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentPort is an autogenerated mock type for the PaymentPort type
type MockPaymentPort struct {
	mock.Mock
}

type MockPaymentPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentPort) EXPECT() *MockPaymentPort_Expecter {
	return &MockPaymentPort_Expecter{mock: &_m.Mock}
}

// Capture provides a mock function with given fields: ctx, externalReference, amount
func (_m *MockPaymentPort) Capture(ctx context.Context, externalReference string, amount model.MoneyModel) error {
	ret := _m.Called(ctx, externalReference, amount)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.MoneyModel) error); ok {
		r0 = rf(ctx, externalReference, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentPort_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type MockPaymentPort_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
//   - externalReference string
//   - amount model.MoneyModel
func (_e *MockPaymentPort_Expecter) Capture(ctx interface{}, externalReference interface{}, amount interface{}) *MockPaymentPort_Capture_Call {
	return &MockPaymentPort_Capture_Call{Call: _e.mock.On("Capture", ctx, externalReference, amount)}
}

func (_c *MockPaymentPort_Capture_Call) Run(run func(ctx context.Context, externalReference string, amount model.MoneyModel)) *MockPaymentPort_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.MoneyModel))
	})
	return _c
}

func (_c *MockPaymentPort_Capture_Call) Return(_a0 error) *MockPaymentPort_Capture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentPort_Capture_Call) RunAndReturn(run func(context.Context, string, model.MoneyModel) error) *MockPaymentPort_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// Forfeit provides a mock function with given fields: ctx, externalReference
func (_m *MockPaymentPort) Forfeit(ctx context.Context, externalReference string) error {
	ret := _m.Called(ctx, externalReference)

	if len(ret) == 0 {
		panic("no return value specified for Forfeit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, externalReference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentPort_Forfeit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forfeit'
type MockPaymentPort_Forfeit_Call struct {
	*mock.Call
}

// Forfeit is a helper method to define mock.On call
//   - ctx context.Context
//   - externalReference string
func (_e *MockPaymentPort_Expecter) Forfeit(ctx interface{}, externalReference interface{}) *MockPaymentPort_Forfeit_Call {
	return &MockPaymentPort_Forfeit_Call{Call: _e.mock.On("Forfeit", ctx, externalReference)}
}

func (_c *MockPaymentPort_Forfeit_Call) Run(run func(ctx context.Context, externalReference string)) *MockPaymentPort_Forfeit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentPort_Forfeit_Call) Return(_a0 error) *MockPaymentPort_Forfeit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentPort_Forfeit_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentPort_Forfeit_Call {
	_c.Call.Return(run)
	return _c
}

// Hold provides a mock function with given fields: ctx, userID, amount, currency, reference
func (_m *MockPaymentPort) Hold(ctx context.Context, userID uint64, amount model.MoneyModel, currency string, reference string) (string, error) {
	ret := _m.Called(ctx, userID, amount, currency, reference)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, model.MoneyModel, string, string) (string, error)); ok {
		return rf(ctx, userID, amount, currency, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, model.MoneyModel, string, string) string); ok {
		r0 = rf(ctx, userID, amount, currency, reference)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, model.MoneyModel, string, string) error); ok {
		r1 = rf(ctx, userID, amount, currency, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentPort_Hold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hold'
type MockPaymentPort_Hold_Call struct {
	*mock.Call
}

// Hold is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - amount model.MoneyModel
//   - currency string
//   - reference string
func (_e *MockPaymentPort_Expecter) Hold(ctx interface{}, userID interface{}, amount interface{}, currency interface{}, reference interface{}) *MockPaymentPort_Hold_Call {
	return &MockPaymentPort_Hold_Call{Call: _e.mock.On("Hold", ctx, userID, amount, currency, reference)}
}

func (_c *MockPaymentPort_Hold_Call) Run(run func(ctx context.Context, userID uint64, amount model.MoneyModel, currency string, reference string)) *MockPaymentPort_Hold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(model.MoneyModel), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockPaymentPort_Hold_Call) Return(externalReference string, err error) *MockPaymentPort_Hold_Call {
	_c.Call.Return(externalReference, err)
	return _c
}

func (_c *MockPaymentPort_Hold_Call) RunAndReturn(run func(context.Context, uint64, model.MoneyModel, string, string) (string, error)) *MockPaymentPort_Hold_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, externalReference
func (_m *MockPaymentPort) Release(ctx context.Context, externalReference string) error {
	ret := _m.Called(ctx, externalReference)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, externalReference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentPort_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockPaymentPort_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - externalReference string
func (_e *MockPaymentPort_Expecter) Release(ctx interface{}, externalReference interface{}) *MockPaymentPort_Release_Call {
	return &MockPaymentPort_Release_Call{Call: _e.mock.On("Release", ctx, externalReference)}
}

func (_c *MockPaymentPort_Release_Call) Run(run func(ctx context.Context, externalReference string)) *MockPaymentPort_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentPort_Release_Call) Return(_a0 error) *MockPaymentPort_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentPort_Release_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentPort_Release_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentPort creates a new instance of MockPaymentPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentPort {
	mock := &MockPaymentPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
