// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	ports "auction/internal/modules/deposit/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuctionConfigPort is an autogenerated mock type for the AuctionConfigPort type
type MockAuctionConfigPort struct {
	mock.Mock
}

type MockAuctionConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionConfigPort) EXPECT() *MockAuctionConfigPort_Expecter {
	return &MockAuctionConfigPort_Expecter{mock: &_m.Mock}
}

// GetRequiredDeposit provides a mock function with given fields: ctx, auctionID
func (_m *MockAuctionConfigPort) GetRequiredDeposit(ctx context.Context, auctionID uint64) (ports.AuctionDepositConfig, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for GetRequiredDeposit")
	}

	var r0 ports.AuctionDepositConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (ports.AuctionDepositConfig, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ports.AuctionDepositConfig); ok {
		r0 = rf(ctx, auctionID)
	} else {
		r0 = ret.Get(0).(ports.AuctionDepositConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionConfigPort_GetRequiredDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequiredDeposit'
type MockAuctionConfigPort_GetRequiredDeposit_Call struct {
	*mock.Call
}

// GetRequiredDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
func (_e *MockAuctionConfigPort_Expecter) GetRequiredDeposit(ctx interface{}, auctionID interface{}) *MockAuctionConfigPort_GetRequiredDeposit_Call {
	return &MockAuctionConfigPort_GetRequiredDeposit_Call{Call: _e.mock.On("GetRequiredDeposit", ctx, auctionID)}
}

func (_c *MockAuctionConfigPort_GetRequiredDeposit_Call) Run(run func(ctx context.Context, auctionID uint64)) *MockAuctionConfigPort_GetRequiredDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuctionConfigPort_GetRequiredDeposit_Call) Return(_a0 ports.AuctionDepositConfig, _a1 error) *MockAuctionConfigPort_GetRequiredDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionConfigPort_GetRequiredDeposit_Call) RunAndReturn(run func(context.Context, uint64) (ports.AuctionDepositConfig, error)) *MockAuctionConfigPort_GetRequiredDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionConfigPort creates a new instance of MockAuctionConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionConfigPort {
	mock := &MockAuctionConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
