// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuctionWinnerPort is an autogenerated mock type for the AuctionWinnerPort type
type MockAuctionWinnerPort struct {
	mock.Mock
}

type MockAuctionWinnerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuctionWinnerPort) EXPECT() *MockAuctionWinnerPort_Expecter {
	return &MockAuctionWinnerPort_Expecter{mock: &_m.Mock}
}

// GetWinnerUserID provides a mock function with given fields: ctx, auctionID
func (_m *MockAuctionWinnerPort) GetWinnerUserID(ctx context.Context, auctionID uint64) (*uint64, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for GetWinnerUserID")
	}

	var r0 *uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*uint64, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *uint64); ok {
		r0 = rf(ctx, auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuctionWinnerPort_GetWinnerUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWinnerUserID'
type MockAuctionWinnerPort_GetWinnerUserID_Call struct {
	*mock.Call
}

// GetWinnerUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionID uint64
func (_e *MockAuctionWinnerPort_Expecter) GetWinnerUserID(ctx interface{}, auctionID interface{}) *MockAuctionWinnerPort_GetWinnerUserID_Call {
	return &MockAuctionWinnerPort_GetWinnerUserID_Call{Call: _e.mock.On("GetWinnerUserID", ctx, auctionID)}
}

func (_c *MockAuctionWinnerPort_GetWinnerUserID_Call) Run(run func(ctx context.Context, auctionID uint64)) *MockAuctionWinnerPort_GetWinnerUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAuctionWinnerPort_GetWinnerUserID_Call) Return(_a0 *uint64, _a1 error) *MockAuctionWinnerPort_GetWinnerUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuctionWinnerPort_GetWinnerUserID_Call) RunAndReturn(run func(context.Context, uint64) (*uint64, error)) *MockAuctionWinnerPort_GetWinnerUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuctionWinnerPort creates a new instance of MockAuctionWinnerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuctionWinnerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuctionWinnerPort {
	mock := &MockAuctionWinnerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
