// Code generated by mockery v2.53.5. DO NOT EDIT.

package testmocks

import (
	ports "auction/internal/modules/deposit/ports"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// ListUnpublished provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) ListUnpublished(ctx context.Context, limit int) ([]ports.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUnpublished")
	}

	var r0 []ports.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]ports.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []ports.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_ListUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnpublished'
type MockOutboxRepository_ListUnpublished_Call struct {
	*mock.Call
}

// ListUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) ListUnpublished(ctx interface{}, limit interface{}) *MockOutboxRepository_ListUnpublished_Call {
	return &MockOutboxRepository_ListUnpublished_Call{Call: _e.mock.On("ListUnpublished", ctx, limit)}
}

func (_c *MockOutboxRepository_ListUnpublished_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_ListUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_ListUnpublished_Call) Return(_a0 []ports.OutboxEvent, _a1 error) *MockOutboxRepository_ListUnpublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_ListUnpublished_Call) RunAndReturn(run func(context.Context, int) ([]ports.OutboxEvent, error)) *MockOutboxRepository_ListUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, id
func (_m *MockOutboxRepository) MarkPublished(ctx context.Context, id uint64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockOutboxRepository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockOutboxRepository_Expecter) MarkPublished(ctx interface{}, id interface{}) *MockOutboxRepository_MarkPublished_Call {
	return &MockOutboxRepository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *MockOutboxRepository_MarkPublished_Call) Run(run func(ctx context.Context, id uint64)) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkPublished_Call) Return(_a0 bool, _a1 error) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_MarkPublished_Call) RunAndReturn(run func(context.Context, uint64) (bool, error)) *MockOutboxRepository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, event
func (_m *MockOutboxRepository) Save(ctx context.Context, event ports.OutboxEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.OutboxEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOutboxRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - event ports.OutboxEvent
func (_e *MockOutboxRepository_Expecter) Save(ctx interface{}, event interface{}) *MockOutboxRepository_Save_Call {
	return &MockOutboxRepository_Save_Call{Call: _e.mock.On("Save", ctx, event)}
}

func (_c *MockOutboxRepository_Save_Call) Run(run func(ctx context.Context, event ports.OutboxEvent)) *MockOutboxRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.OutboxEvent))
	})
	return _c
}

func (_c *MockOutboxRepository_Save_Call) Return(_a0 error) *MockOutboxRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_Save_Call) RunAndReturn(run func(context.Context, ports.OutboxEvent) error) *MockOutboxRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
