package errs

import "errors"

var (
	ErrAuctionNotFound                       = errors.New("auction not found")
	ErrBidNotFound                           = errors.New("bid not found")
	ErrConcurrencyConflict                   = errors.New("concurrency conflict: resource was modified")
	ErrTransactionFailed                     = errors.New("transaction failed")
	ErrAuctionIDRequired                     = errors.New("auction id must be greater than zero")
	ErrListingIDRequired                     = errors.New("listing id must be greater than zero")
	ErrEndTimeRequired                       = errors.New("end time is required")
	ErrAuctionCanOnlyStartFromDraft          = errors.New("auction can only be started from draft state")
	ErrBidsOnlyOnActiveAuctions              = errors.New("bids can only be placed on active auctions")
	ErrAuctionExpired                        = errors.New("auction has expired")
	ErrAuctionCanOnlyCloseFromActive         = errors.New("auction can only be closed from active state")
	ErrAuctionCanOnlyCancelFromDraftOrActive = errors.New("auction can only be cancelled from draft or active state")
	ErrFirstBidMustBePositive                = errors.New("first bid amount must be greater than zero")
	ErrBidMustExceedHighest                  = errors.New("bid amount must exceed current highest bid")
	ErrBidDuplicateIdempotencyKey            = errors.New("bid with the same idempotency key already exists")
	ErrBidIDRequired                         = errors.New("bid id must be greater than zero")
	ErrUserIDRequired                        = errors.New("user id must be greater than zero")
	ErrEndTimeMustBeInFuture                 = errors.New("end time must be in the future")
	ErrStartTimeMustBeInFuture               = errors.New("start time must be in the future")
	ErrStartTimeMustBeBeforeEndTime          = errors.New("start time must be before end time")
	ErrInvalidAuctionState                   = errors.New("invalid auction state")
	ErrUnsupportedTradingMode                = errors.New("unsupported trading mode")
	ErrStartingPriceRequired                 = errors.New("starting price is required for this trading mode")
	ErrDutchBidMustMatchPrice                = errors.New("dutch bid must match the current price")
	ErrDutchPriceNotAvailable                = errors.New("dutch current price is not available")
	ErrFixedPriceMismatch                    = errors.New("fixed price bid must match the listing price")
	ErrFixedPriceNotConfigured               = errors.New("fixed price auction is not configured with a price")
	ErrProxyMaxTooLow                        = errors.New("proxy max bid is too low to become the leader")
	ErrReserveNotMet                         = errors.New("reserve price was not met")
	ErrListingNotAvailable                   = errors.New("listing does not exist or is not available for auction")
)
