// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bids.sql

package sqlcgen

import (
	"context"
)

const getBidderIDByBidID = `-- name: GetBidderIDByBidID :one
SELECT user_id
FROM bids
WHERE id = $1
`

func (q *Queries) GetBidderIDByBidID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getBidderIDByBidID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getPreviousHighestBidder = `-- name: GetPreviousHighestBidder :one
SELECT user_id
FROM bids
WHERE auction_id = $1
  AND user_id <> $2
ORDER BY amount_in_cents DESC, created_at DESC
LIMIT 1
`

type GetPreviousHighestBidderParams struct {
	AuctionID int64
	UserID    int64
}

func (q *Queries) GetPreviousHighestBidder(ctx context.Context, arg GetPreviousHighestBidderParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPreviousHighestBidder, arg.AuctionID, arg.UserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
