// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Notification struct {
	ID             int64
	UserID         int64
	Category       string
	Type           string
	Title          string
	Body           string
	Payload        []byte
	Channels       []string
	IdempotencyKey string
	ReadAt         *time.Time
	CreatedAt      time.Time
}

type NotificationOutbox struct {
	ID            int64
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
	CreatedAt     time.Time
	PublishedAt   *time.Time
}

type NotificationPreference struct {
	UserID      int64
	Preferences []byte
	UpdatedAt   time.Time
}

type Watchlist struct {
	ID        int64
	UserID    int64
	SpuID     int64
	CreatedAt time.Time
}
