// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcgen

import (
	"context"
)

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, category, type, title, body, payload, channels, idempotency_key, read_at, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.Channels,
		&i.IdempotencyKey,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    user_id, category, type, title, body, payload, channels, idempotency_key, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, user_id, category, type, title, body, payload, channels, idempotency_key, read_at, created_at
`

type InsertNotificationParams struct {
	UserID         int64
	Category       string
	Type           string
	Title          string
	Body           string
	Payload        []byte
	Channels       []string
	IdempotencyKey string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Category,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.Channels,
		arg.IdempotencyKey,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.Channels,
		&i.IdempotencyKey,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, category, type, title, body, payload, channels, idempotency_key, read_at, created_at
FROM notifications
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.Channels,
			&i.IdempotencyKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsByUser = `-- name: ListUnreadNotificationsByUser :many
SELECT id, user_id, category, type, title, body, payload, channels, idempotency_key, read_at, created_at
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListUnreadNotificationsByUser(ctx context.Context, arg ListUnreadNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.Channels,
			&i.IdempotencyKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = NOW()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = NOW()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
