// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_outbox.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertEmailRequestOutboxEvent = `-- name: InsertEmailRequestOutboxEvent :exec
INSERT INTO notification_outbox (event_id, event_type, schema_version, subject, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id) DO NOTHING
`

type InsertEmailRequestOutboxEventParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertEmailRequestOutboxEvent(ctx context.Context, arg InsertEmailRequestOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertEmailRequestOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Subject,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertNotificationOutboxEvent = `-- name: InsertNotificationOutboxEvent :exec
INSERT INTO notification_outbox (event_id, event_type, schema_version, subject, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNotificationOutboxEventParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertNotificationOutboxEvent(ctx context.Context, arg InsertNotificationOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertNotificationOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Subject,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listUnpublishedNotificationOutboxEvents = `-- name: ListUnpublishedNotificationOutboxEvents :many
SELECT id, event_id, event_type, schema_version, subject, payload, occurred_at, created_at, published_at
FROM notification_outbox
WHERE published_at IS NULL
ORDER BY id ASC
LIMIT $1
`

func (q *Queries) ListUnpublishedNotificationOutboxEvents(ctx context.Context, limit int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedNotificationOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Subject,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationOutboxEventPublished = `-- name: MarkNotificationOutboxEventPublished :execrows
UPDATE notification_outbox
SET published_at = NOW()
WHERE id = $1 AND published_at IS NULL
`

func (q *Queries) MarkNotificationOutboxEventPublished(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationOutboxEventPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
