// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package sqlcgen

import (
	"context"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, preferences, updated_at
FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID int64) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(&i.UserID, &i.Preferences, &i.UpdatedAt)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, preferences, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id) DO UPDATE
SET preferences = EXCLUDED.preferences, updated_at = NOW()
RETURNING user_id, preferences, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID      int64
	Preferences []byte
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences, arg.UserID, arg.Preferences)
	var i NotificationPreference
	err := row.Scan(&i.UserID, &i.Preferences, &i.UpdatedAt)
	return i, err
}
