// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spus.sql

package sqlcgen

import (
	"context"
)

const findSpuTitleByID = `-- name: FindSpuTitleByID :one
SELECT title FROM spus
WHERE id = $1
`

func (q *Queries) FindSpuTitleByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, findSpuTitleByID, id)
	var title string
	err := row.Scan(&title)
	return title, err
}
