// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const getUserEmailByID = `-- name: GetUserEmailByID :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmailByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}
