// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlists.sql

package sqlcgen

import (
	"context"
)

const deleteWatchlist = `-- name: DeleteWatchlist :one
DELETE FROM watchlists
WHERE user_id = $1 AND spu_id = $2
RETURNING id, user_id, spu_id, created_at
`

type DeleteWatchlistParams struct {
	UserID int64
	SpuID  int64
}

func (q *Queries) DeleteWatchlist(ctx context.Context, arg DeleteWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, deleteWatchlist, arg.UserID, arg.SpuID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpuID,
		&i.CreatedAt,
	)
	return i, err
}

const findWatcherIDsBySpuID = `-- name: FindWatcherIDsBySpuID :many
SELECT user_id FROM watchlists
WHERE spu_id = $1
`

func (q *Queries) FindWatcherIDsBySpuID(ctx context.Context, spuID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, findWatcherIDsBySpuID, spuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistsByUser = `-- name: ListWatchlistsByUser :many
SELECT id, user_id, spu_id, created_at FROM watchlists
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWatchlistsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListWatchlistsByUser(ctx context.Context, arg ListWatchlistsByUserParams) ([]Watchlist, error) {
	rows, err := q.db.Query(ctx, listWatchlistsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watchlist
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpuID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchlist = `-- name: UpsertWatchlist :one
INSERT INTO watchlists (user_id, spu_id)
VALUES ($1, $2)
ON CONFLICT (user_id, spu_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, spu_id, created_at
`

type UpsertWatchlistParams struct {
	UserID int64
	SpuID  int64
}

func (q *Queries) UpsertWatchlist(ctx context.Context, arg UpsertWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, upsertWatchlist, arg.UserID, arg.SpuID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpuID,
		&i.CreatedAt,
	)
	return i, err
}
