// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlcgen

import (
	"context"
	"time"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger_accounts (
    owner, balance, frozen_balance, currency, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, owner, balance, frozen_balance, currency, version, created_at, updated_at
`

type CreateLedgerAccountParams struct {
	Owner         string
	Balance       int64
	FrozenBalance int64
	Currency      string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.Owner,
		arg.Balance,
		arg.FrozenBalance,
		arg.Currency,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    account_id, amount, entry_type, operation_id, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, account_id, amount, entry_type, operation_id, created_at
`

type CreateLedgerEntryParams struct {
	AccountID   int64
	Amount      int64
	EntryType   string
	OperationID *int64
	CreatedAt   time.Time
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.AccountID,
		arg.Amount,
		arg.EntryType,
		arg.OperationID,
		arg.CreatedAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.EntryType,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerOperation = `-- name: CreateLedgerOperation :one
INSERT INTO ledger_operations (
    account_id, counterparty_account_id, operation_type, amount, idempotency_key,
    status, reference, description, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, account_id, counterparty_account_id, operation_type, amount,
    idempotency_key, status, reference, description, created_at, updated_at
`

type CreateLedgerOperationParams struct {
	AccountID             int64
	CounterpartyAccountID *int64
	OperationType         string
	Amount                int64
	IdempotencyKey        string
	Status                string
	Reference             *string
	Description           *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreateLedgerOperation(ctx context.Context, arg CreateLedgerOperationParams) (LedgerOperation, error) {
	row := q.db.QueryRow(ctx, createLedgerOperation,
		arg.AccountID,
		arg.CounterpartyAccountID,
		arg.OperationType,
		arg.Amount,
		arg.IdempotencyKey,
		arg.Status,
		arg.Reference,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LedgerOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CounterpartyAccountID,
		&i.OperationType,
		&i.Amount,
		&i.IdempotencyKey,
		&i.Status,
		&i.Reference,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerTransfer = `-- name: CreateLedgerTransfer :one
INSERT INTO ledger_transfers (
    from_account_id, to_account_id, amount, idempotency_key, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, from_account_id, to_account_id, amount, idempotency_key, created_at
`

type CreateLedgerTransferParams struct {
	FromAccountID  int64
	ToAccountID    int64
	Amount         int64
	IdempotencyKey string
	CreatedAt      time.Time
}

func (q *Queries) CreateLedgerTransfer(ctx context.Context, arg CreateLedgerTransferParams) (LedgerTransfer, error) {
	row := q.db.QueryRow(ctx, createLedgerTransfer,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i LedgerTransfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerAccountByID = `-- name: GetLedgerAccountByID :one
SELECT id, owner, balance, frozen_balance, currency, version, created_at, updated_at
FROM ledger_accounts
WHERE id = $1
`

func (q *Queries) GetLedgerAccountByID(ctx context.Context, id int64) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByID, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccountByIDForUpdate = `-- name: GetLedgerAccountByIDForUpdate :one
SELECT id, owner, balance, frozen_balance, currency, version, created_at, updated_at
FROM ledger_accounts
WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetLedgerAccountByIDForUpdate(ctx context.Context, id int64) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByIDForUpdate, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccountByOwner = `-- name: GetLedgerAccountByOwner :one
SELECT id, owner, balance, frozen_balance, currency, version, created_at, updated_at
FROM ledger_accounts
WHERE owner = $1 AND currency = $2
`

type GetLedgerAccountByOwnerParams struct {
	Owner    string
	Currency string
}

func (q *Queries) GetLedgerAccountByOwner(ctx context.Context, arg GetLedgerAccountByOwnerParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByOwner, arg.Owner, arg.Currency)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerAccountByOwnerForUpdate = `-- name: GetLedgerAccountByOwnerForUpdate :one
SELECT id, owner, balance, frozen_balance, currency, version, created_at, updated_at
FROM ledger_accounts
WHERE owner = $1 AND currency = $2 FOR UPDATE
`

type GetLedgerAccountByOwnerForUpdateParams struct {
	Owner    string
	Currency string
}

func (q *Queries) GetLedgerAccountByOwnerForUpdate(ctx context.Context, arg GetLedgerAccountByOwnerForUpdateParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByOwnerForUpdate, arg.Owner, arg.Currency)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerOperationByIdempotency = `-- name: GetLedgerOperationByIdempotency :one
SELECT id, account_id, counterparty_account_id, operation_type, amount,
    idempotency_key, status, reference, description, created_at, updated_at
FROM ledger_operations
WHERE idempotency_key = $1
`

func (q *Queries) GetLedgerOperationByIdempotency(ctx context.Context, idempotencyKey string) (LedgerOperation, error) {
	row := q.db.QueryRow(ctx, getLedgerOperationByIdempotency, idempotencyKey)
	var i LedgerOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CounterpartyAccountID,
		&i.OperationType,
		&i.Amount,
		&i.IdempotencyKey,
		&i.Status,
		&i.Reference,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerTransferByIdempotency = `-- name: GetLedgerTransferByIdempotency :one
SELECT id, from_account_id, to_account_id, amount, idempotency_key, created_at
FROM ledger_transfers
WHERE idempotency_key = $1
`

func (q *Queries) GetLedgerTransferByIdempotency(ctx context.Context, idempotencyKey string) (LedgerTransfer, error) {
	row := q.db.QueryRow(ctx, getLedgerTransferByIdempotency, idempotencyKey)
	var i LedgerTransfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, owner, balance, frozen_balance, currency, version, created_at, updated_at
FROM ledger_accounts
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListLedgerAccountsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLedgerAccounts(ctx context.Context, arg ListLedgerAccountsParams) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccount
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.FrozenBalance,
			&i.Currency,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, amount, entry_type, operation_id, created_at
FROM ledger_entries
WHERE account_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID int64
	Limit     int32
	Offset    int32
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.EntryType,
			&i.OperationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerOperationsByAccount = `-- name: ListLedgerOperationsByAccount :many
SELECT id, account_id, counterparty_account_id, operation_type, amount,
    idempotency_key, status, reference, description, created_at, updated_at
FROM ledger_operations
WHERE account_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListLedgerOperationsByAccountParams struct {
	AccountID int64
	Limit     int32
	Offset    int32
}

func (q *Queries) ListLedgerOperationsByAccount(ctx context.Context, arg ListLedgerOperationsByAccountParams) ([]LedgerOperation, error) {
	rows, err := q.db.Query(ctx, listLedgerOperationsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerOperation
	for rows.Next() {
		var i LedgerOperation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CounterpartyAccountID,
			&i.OperationType,
			&i.Amount,
			&i.IdempotencyKey,
			&i.Status,
			&i.Reference,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerAccountBalance = `-- name: UpdateLedgerAccountBalance :one
UPDATE ledger_accounts
SET balance = $2, frozen_balance = $3, version = $4, updated_at = $5
WHERE id = $1 AND version = $6
RETURNING id, owner, balance, frozen_balance, currency, version, created_at, updated_at
`

type UpdateLedgerAccountBalanceParams struct {
	ID            int64
	Balance       int64
	FrozenBalance int64
	Version       int64
	UpdatedAt     time.Time
	Version_2     int64
}

func (q *Queries) UpdateLedgerAccountBalance(ctx context.Context, arg UpdateLedgerAccountBalanceParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccountBalance,
		arg.ID,
		arg.Balance,
		arg.FrozenBalance,
		arg.Version,
		arg.UpdatedAt,
		arg.Version_2,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
