// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Payment struct {
	ID            int64
	UserID        int64
	AmountCents   int64
	Currency      string
	Status        string
	OutTradeNo    string
	QrCodeUrl     *string
	AlipayTradeNo *string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PaymentsOutbox struct {
	ID            int64
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
	CreatedAt     time.Time
	PublishedAt   *time.Time
}

type Withdrawal struct {
	ID              int64
	UserID          int64
	LedgerAccountID int64
	AlipayAccount   string
	AlipayRealName  string
	AmountCents     int64
	Currency        string
	Status          string
	OutBizNo        string
	FrozenOpID      *string
	AlipayOrderID   *string
	FailReason      *string
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
