// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertPaymentOutboxEvent = `-- name: InsertPaymentOutboxEvent :exec
INSERT INTO payments_outbox (event_id, event_type, schema_version, subject, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPaymentOutboxEventParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	Subject       string
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertPaymentOutboxEvent(ctx context.Context, arg InsertPaymentOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertPaymentOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.Subject,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listUnpublishedPaymentOutboxEvents = `-- name: ListUnpublishedPaymentOutboxEvents :many
SELECT id, event_id, event_type, schema_version, subject, payload, occurred_at, created_at, published_at
FROM payments_outbox
WHERE published_at IS NULL
ORDER BY id ASC
LIMIT $1
`

func (q *Queries) ListUnpublishedPaymentOutboxEvents(ctx context.Context, limit int32) ([]PaymentsOutbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedPaymentOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentsOutbox
	for rows.Next() {
		var i PaymentsOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Subject,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentOutboxEventPublished = `-- name: MarkPaymentOutboxEventPublished :execrows
UPDATE payments_outbox
SET published_at = NOW()
WHERE id = $1 AND published_at IS NULL
`

func (q *Queries) MarkPaymentOutboxEventPublished(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPaymentOutboxEventPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
