// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlcgen

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    user_id, amount_cents, currency, status, out_trade_no, qr_code_url, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, user_id, amount_cents, currency, status, out_trade_no, qr_code_url, alipay_trade_no, version, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID      int64
	AmountCents int64
	Currency    string
	Status      string
	OutTradeNo  string
	QrCodeUrl   *string
	Version     int64
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.OutTradeNo,
		arg.QrCodeUrl,
		arg.Version,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutTradeNo,
		&i.QrCodeUrl,
		&i.AlipayTradeNo,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, amount_cents, currency, status, out_trade_no, qr_code_url, alipay_trade_no, version, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutTradeNo,
		&i.QrCodeUrl,
		&i.AlipayTradeNo,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOutTradeNo = `-- name: GetPaymentByOutTradeNo :one
SELECT id, user_id, amount_cents, currency, status, out_trade_no, qr_code_url, alipay_trade_no, version, created_at, updated_at
FROM payments
WHERE out_trade_no = $1
`

func (q *Queries) GetPaymentByOutTradeNo(ctx context.Context, outTradeNo string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOutTradeNo, outTradeNo)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutTradeNo,
		&i.QrCodeUrl,
		&i.AlipayTradeNo,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET status = $1, alipay_trade_no = $2, version = $3, updated_at = NOW()
WHERE id = $4 AND version = $5
RETURNING id, user_id, amount_cents, currency, status, out_trade_no, qr_code_url, alipay_trade_no, version, created_at, updated_at
`

type UpdatePaymentParams struct {
	Status        string
	AlipayTradeNo *string
	Version       int64
	ID            int64
	Version_2     int64
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.Status,
		arg.AlipayTradeNo,
		arg.Version,
		arg.ID,
		arg.Version_2,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutTradeNo,
		&i.QrCodeUrl,
		&i.AlipayTradeNo,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
