// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdrawals.sql

package sqlcgen

import (
	"context"
)

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (
    user_id, ledger_account_id, alipay_account, alipay_real_name, amount_cents, currency, status, out_biz_no, frozen_op_id, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
)
RETURNING id, user_id, ledger_account_id, alipay_account, alipay_real_name, amount_cents, currency, status, out_biz_no, frozen_op_id, alipay_order_id, fail_reason, version, created_at, updated_at
`

type CreateWithdrawalParams struct {
	UserID          int64
	LedgerAccountID int64
	AlipayAccount   string
	AlipayRealName  string
	AmountCents     int64
	Currency        string
	Status          string
	OutBizNo        string
	FrozenOpID      *string
	Version         int64
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.UserID,
		arg.LedgerAccountID,
		arg.AlipayAccount,
		arg.AlipayRealName,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.OutBizNo,
		arg.FrozenOpID,
		arg.Version,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LedgerAccountID,
		&i.AlipayAccount,
		&i.AlipayRealName,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutBizNo,
		&i.FrozenOpID,
		&i.AlipayOrderID,
		&i.FailReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalByID = `-- name: GetWithdrawalByID :one
SELECT id, user_id, ledger_account_id, alipay_account, alipay_real_name, amount_cents, currency, status, out_biz_no, frozen_op_id, alipay_order_id, fail_reason, version, created_at, updated_at
FROM withdrawals
WHERE id = $1
`

func (q *Queries) GetWithdrawalByID(ctx context.Context, id int64) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalByID, id)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LedgerAccountID,
		&i.AlipayAccount,
		&i.AlipayRealName,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutBizNo,
		&i.FrozenOpID,
		&i.AlipayOrderID,
		&i.FailReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalByOutBizNo = `-- name: GetWithdrawalByOutBizNo :one
SELECT id, user_id, ledger_account_id, alipay_account, alipay_real_name, amount_cents, currency, status, out_biz_no, frozen_op_id, alipay_order_id, fail_reason, version, created_at, updated_at
FROM withdrawals
WHERE out_biz_no = $1
`

func (q *Queries) GetWithdrawalByOutBizNo(ctx context.Context, outBizNo string) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalByOutBizNo, outBizNo)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LedgerAccountID,
		&i.AlipayAccount,
		&i.AlipayRealName,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutBizNo,
		&i.FrozenOpID,
		&i.AlipayOrderID,
		&i.FailReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWithdrawal = `-- name: UpdateWithdrawal :one
UPDATE withdrawals
SET status = $1, alipay_order_id = $2, fail_reason = $3, version = $4, updated_at = NOW()
WHERE id = $5 AND version = $6
RETURNING id, user_id, ledger_account_id, alipay_account, alipay_real_name, amount_cents, currency, status, out_biz_no, frozen_op_id, alipay_order_id, fail_reason, version, created_at, updated_at
`

type UpdateWithdrawalParams struct {
	Status        string
	AlipayOrderID *string
	FailReason    *string
	Version       int64
	ID            int64
	Version_2     int64
}

func (q *Queries) UpdateWithdrawal(ctx context.Context, arg UpdateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, updateWithdrawal,
		arg.Status,
		arg.AlipayOrderID,
		arg.FailReason,
		arg.Version,
		arg.ID,
		arg.Version_2,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LedgerAccountID,
		&i.AlipayAccount,
		&i.AlipayRealName,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.OutBizNo,
		&i.FrozenOpID,
		&i.AlipayOrderID,
		&i.FailReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
